--[[---------------------------------------------
-------------------------------------------------
--
-- forageDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------
--old scavenges table (for backwards compatibility)
scavenges = {};
scavenges.plants = {};
scavenges.insects = {};
scavenges.fishbait = {};
scavenges.mushrooms = {};
scavenges.berries = {};
scavenges.forestGoods = {};
scavenges.medicinalPlants = {};
-------------------------------------------------
-------------------------------------------------
local worldSprites = {
	wildPlants = {
		{ "d_plants_1_11" },
		{ "d_plants_1_12" },
		{ "d_plants_1_13" },
		{ "d_plants_1_14" },
		{ "d_plants_1_15" },
	},
	smallTrees = {
		{ "media/textures/Foraging/worldSprites/smallTree_worldSprite.png" },
		{ "media/textures/Foraging/worldSprites/smallTree2_worldSprite.png" },
	},
	berryBushes = {
		{ "f_bushes_1_4", "f_bushes_1_68", "f_bushes_1_84" },
		{ "f_bushes_1_4", "f_bushes_1_68", "f_bushes_1_88" },
	},
	bushes = {
		{ "f_bushes_1_64" },
		{ "f_bushes_1_65" },
		{ "f_bushes_1_66" },
	},
	shrubs = {
		{ "d_plants_1_19" },
		{ "d_plants_1_20" },
		{ "d_plants_1_21" },
		{ "d_plants_1_22" },
		{ "d_plants_1_23" },
		{ "f_bushes_1_68" },
		{ "f_bushes_1_77" },
		{ "f_bushes_1_78" },
	},
	vines = {
		{ "d_plants_1_38" },
		{ "d_plants_1_49" },
		{ "d_plants_1_50" },
	},
};
-------------------------------------------------
-------------------------------------------------
local function iterList(_list)
	local list = _list;
	local size = list:size() - 1;
	local i = -1;
	return function()
		i = i + 1;
		if i <= size and not list:isEmpty() then
			return list:get(i), i;
		end;
	end;
end
-------------------------------------------------
-------------------------------------------------
--[[--======== Spawn Functions ========--]]--

local function doPoisonItemSpawn(_character, _inventory, _itemDef, _items)
	if _itemDef.poisonChance and _itemDef.poisonPowerMin and _itemDef.poisonPowerMax then
		if _itemDef.poisonChance > 0 and _itemDef.poisonPowerMax > 0 then
			local perkLevel = forageSystem.getPerkLevel(_character, _itemDef);
			--increase poison chance by up to 50% for level 0
			if ZombRand(100) < _itemDef.poisonChance + ((10 - perkLevel) * 5) then
				for item in iterList(_items) do
					item:setPoisonPower(ZombRand(_itemDef.poisonPowerMin, _itemDef.poisonPowerMax) + 1);
					item:setPoisonDetectionLevel(_itemDef.poisonDetectionLevel or 0);
					item:setUseForPoison(item:getHungChange());
				end;
			end;
		end;
	end;
	return _items; ----custom spawn scripts must return an arraylist of items (or nil)
end

local function doWildFoodSpawn(_character, _inventory, _itemDef, _items)
	-- Randomize the size of the item
	local perkLevel = forageSystem.getPerkLevel(_character, _itemDef);
	for item in iterList(_items) do
		item:setName(item:getDisplayName() .. " (" .. getText("UI_foraging_WildFood") .. ")");
		--25 to 75 percent size
		local sizeModifier = ((ZombRand(50) + 25) / 100);
		--add up to 110% for perk level
		sizeModifier = sizeModifier + ((ZombRand(perkLevel) + 1) / 10)
		-- Set the item's stats depending on the random size
		if item:getBaseHunger() <= -0.02 then
			item:setBaseHunger(item:getBaseHunger() * sizeModifier);
			item:setHungChange(item:getHungChange() * sizeModifier);
			item:setCarbohydrates(item:getCarbohydrates() * sizeModifier);
			item:setLipids(item:getLipids() * sizeModifier);
			item:setProteins(item:getProteins() * sizeModifier);
			item:setCalories(item:getCalories() * sizeModifier);
			item:setUnhappyChange(item:getUnhappyChange() * sizeModifier);
			--item:multiplyFoodValues(sizeModifier);
			--item:setActualWeight(item:getActualWeight() * sizeModifier);
		end;
		--set random age based on perkLevel and random chance
		local randomAge = 0;
		if ZombRand(10) + 1 < perkLevel then
			randomAge = ZombRand((item:getOffAge() * 1000)) / 1000;
		else
			randomAge = ZombRand((item:getOffAgeMax() * 1000)) / 1000;
		end;
		item:setAge(randomAge);
	end;
	return _items; --custom spawn scripts must return an arraylist of items (or nil)
end

local function doWildCropSpawn(_character, _inventory, _itemDef, _items)
	local seedTable = {
		["Base.Carrots"] = "farming.CarrotSeed",
		["farming.BloomingBroccoli"] = "farming.BroccoliSeed",
		["farming.RedRadish"] = "farming.RedRadishSeed",
		["farming.Strewberrie"] = "farming.StrewberrieSeed",
		["farming.Potato"] = "farming.PotatoSeed",
		["farming.Tomato"] = "farming.TomatoSeed",
		["farming.Cabbage"] = "farming.CabbageSeed",
	};
	--75% chance to generate a few seeds
	if seedTable[_itemDef.type] then
		local seedChance = 75;
		if ZombRand(100) <= seedChance then
			local seedAmount = ZombRand(20) + 1;
			local seedItemType = seedTable[_itemDef.type];
			_inventory:AddItems(seedItemType, seedAmount);
			for i = 1, seedAmount do
				_items:add(InventoryItemFactory.CreateItem(seedItemType));
			end;
		end;
	end;
	return _items; --custom spawn scripts must return an arraylist of items (or nil)
end

local function doJunkWeaponSpawn(_character, _inventory, _itemDef, _items)
	for item in iterList(_items) do
		local conditionMax = item:getConditionMax();
		if conditionMax > 0 then
			item:setCondition(ZombRand(conditionMax) + 1); -- Randomize the weapon condition
		end;
	end;
	return _items; --custom spawn scripts must return an arraylist of items (or nil)
end

local function doDeadTrapAnimalSpawn(_character, _inventory, _itemDef, _items)
	for item in iterList(_items) do
		--search for trap animal definition
		for _, trapDef in pairs(Animals) do
			if trapDef.item == _itemDef.type then
				-- Randomize the hunger reduction of the animal
				local size = ZombRand(trapDef.minSize, trapDef.maxSize);
				local typicalSize = item:getBaseHunger() * -100;
				local statsModifier = size / typicalSize;
				-- Set the animal's stats depending on the random size
				item:setBaseHunger(item:getBaseHunger() * statsModifier);
				item:setHungChange(item:getHungChange() * statsModifier);
				item:setActualWeight(item:getActualWeight() * statsModifier);
				item:setCarbohydrates(item:getCarbohydrates() * statsModifier);
				item:setLipids(item:getLipids() * statsModifier);
				item:setProteins(item:getProteins() * statsModifier);
				item:setCalories(item:getCalories() * statsModifier);
			end;
		end;
		item:setAge(ZombRand((item:getOffAgeMax() * 1000)) / 1000);
	end;
	return _items; --custom spawn scripts must return an arraylist of items (or nil)
end
-------------------------------------------------
-------------------------------------------------

--[[--======== forageDefaultDefs ========--
    ---- default values (applied if missing from item definition)
]]--

forageDefaultDefs = {
	---- default values (applied if missing from item definition)
	defaultItemDef = {
		type                    = "Base.MissingItemType",                       --item type including module
		minCount                = 1,                                            --minimum amount of items to pick up
		maxCount                = 1,                                            --maximum amount of items to pick up
		skill                   = 0,                                            --skill level required to see the item
		perks                   = { "PlantScavenging" },                        --perks required - can be multiple perks, skill level will be averaged
		xp                      = 10,                                           --xp reward on pickup - divide by 3 for spotting xp - is awarded to all perks required
		---
		recipes                 = {},                                           --recipes required to see the item
		traits                  = {},                                           --traits required to see the item
		itemTags                = {},                                           --itemTags required to see the item (digPlow etc)
		---
		categories              = { "Junk" },                                   --categories the item is a part of
		rainChance              = 0,                                            --rain chance modifier (percent)
		snowChance              = 0,                                            --snow chance modifier (percent)
		---
		zones           = {                                                     --zones where the item can be found
			Forest              = 1,                                            --[zone name] = chance for item in this zone
			DeepForest          = 1,
			Vegitation          = 1,
			FarmLand            = 1,
			Farm                = 1,
			TrailerPark         = 1,
			TownZone            = 1,
			Nav                 = 1,
		},
		---
		months                  = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },    --months when the item can be found
		bonusMonths             = {},                                           --months when the item is more common (must be in months)
		malusMonths             = {},                                           --months when the item is less common (must be in months)
		spawnFuncs              = {},                                           --custom spawn function when item is picked up
		forceOutside            = true,                                         --item must be outside
		isOnWater               = false,                                        --item can be on water
		forceOnWater            = false,                                        --item must be on water
		isMover                 = false,                                        --does nothing, ignored
		canBeAboveFloor         = false,                                        --does nothing, ignored
		doIsoMarkerObject       = false,                                        --create an IsoMarker temp object on square
		doIsoMarkerSprite       = nil,                                          --use a custom sprite/sprites for IsoMarker
		canBeOnTreeSquare       = false,                                        --can occupy the same square as an IsoTree
		---
		poisonChance            = 0,                                            --chance the item is poisoned
		poisonPowerMin          = 0,                                            --minimum amount of poison to apply
		poisonPowerMax          = 0,                                            --maximum amount of poison to apply
		poisonDetectionLevel    = 0,                                            --level required to detect the poison
		---
		itemSizeModifier        = 0,                                            --increase or decrease item weight in vision radius checking
		isItemOverrideSize      = false,                                        --use only itemSizeModifier in vision radius checking - not the real item weight
	},
	-- default values (applied if missing from zone definition)
	defaultZoneDef  = {
		name                    = "Unknown",
		densityMin              = 1,
		densityMax              = 1,
		refillPercent           = 1,
		abundanceSetting        = "NatureAbundance",
	},
	-- default values (applied if missing from category definition)
	defaultCatDef   = {
		chance                  = 1,
		name                    = "Unknown",
		typeCategory            = "Other",
		showOptionPerk          = "PlantScavenging",
		showCategoryLevel       = 0,
		validFloors             = { "ANY" },
		validFunc               = nil,
		zoneChance = {
			Forest              = 1,
			DeepForest          = 1,
			Vegitation          = 1,
			FarmLand            = 1,
			Farm                = 1,
			TrailerPark         = 1,
			TownZone            = 1,
			Nav                 = 1,
		},
		spriteAffinities        = {},
		chanceToMoveIcon        = 0,
	},
};

--[[--======== forageZones ========--
]]--

forageZones = {
	DeepForest = {
		name = "DeepForest",
		densityMin = 12,
		densityMax = 15,
		refillPercent = 7,
		abundanceSetting = "NatureAbundance",
	},
	FarmLand = {
		name = "FarmLand",
		densityMin = 3,
		densityMax = 7.5,
		refillPercent = 5,
		abundanceSetting = "NatureAbundance",
	},
	Farm = {
		name = "Farm",
		densityMin = 3,
		densityMax = 7.5,
		refillPercent = 5,
		abundanceSetting = "NatureAbundance",
	},
	Forest = {
		name = "Forest",
		densityMin = 9,
		densityMax = 12,
		refillPercent = 7,
		abundanceSetting = "NatureAbundance",
	},
	Nav = {
		name = "Nav",
		densityMin = 3,
		densityMax = 7.5,
		refillPercent = 3,
		abundanceSetting = "OtherLoot",
	},
	TownZone = {
		name = "TownZone",
		densityMin = 3,
		densityMax = 7.5,
		refillPercent = 3,
		abundanceSetting = "OtherLoot",
	},
	TrailerPark = {
		name = "TrailerPark",
		densityMin = 1.5,
		densityMax = 7.5,
		refillPercent = 3,
		abundanceSetting = "OtherLoot",
	},
	Vegitation = {
		name = "Vegitation",
		densityMin = 6,
		densityMax = 10.5,
		refillPercent = 5,
		abundanceSetting = "NatureAbundance",
	},
};

--[[--======== forageCategories ========--
]]--

forageCategories = {
	["Animals"] = {
		chance = 15,
		name = "Animals",
		typeCategory = "Animals",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 5,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 15,
			Forest          = 15,
			Vegitation      = 25,
			FarmLand        = 20,
			Farm            = 20,
			TrailerPark     = 15,
			TownZone        = 15,
			Nav             = 5,
		},
	},
	["Berries"] = {
		chance = 25,
		name = "Berries",
		typeCategory = "Food",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 2,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			DeepForest      = 40,
			Forest          = 30,
			Vegitation      = 20,
			FarmLand        = 15,
			Farm            = 15,
			TrailerPark     = 5,
			TownZone        = 5,
			Nav             = 1,
		},
	},
	["Fruits"] = {
		chance = 15,
		name = "Fruits",
		typeCategory = "Food",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 2,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			Forest          = 15,
			DeepForest      = 15,
			Vegitation      = 15,
			FarmLand        = 25,
			Farm            = 25,
			TrailerPark     = 10,
			TownZone        = 5,
			Nav             = 1,
		},
	},
	["Vegetables"] = {
		chance = 15,
		name = "Vegetables",
		typeCategory = "Food",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 5,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			DeepForest      = 15,
			Forest          = 15,
			Vegitation      = 15,
			FarmLand        = 25,
			Farm            = 25,
			TrailerPark     = 10,
			TownZone        = 5,
			Nav             = 1,
		},
	},
	["Mushrooms"] = {
		chance = 15,
		name = "Mushrooms",
		typeCategory = "Food",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 4,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			DeepForest      = 40,
			Forest          = 30,
			Vegitation      = 20,
			FarmLand        = 15,
			Farm            = 15,
			TrailerPark     = 5,
			TownZone        = 5,
			Nav             = 1,
		},
	},
	["FishBait"] = {
		chance = 10,
		name = "FishBait",
		typeCategory = "Animals",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 3,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			DeepForest      = 10,
			Forest          = 10,
			Vegitation      = 10,
			FarmLand        = 10,
			Farm            = 10,
			TrailerPark     = 10,
			TownZone        = 10,
			Nav             = 1,
		},
	},
	--this is an empty category
	["ForestGoods"] = {
		chance = 0,
		name = "ForestGoods",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 0,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 0,
			Forest          = 0,
			Vegitation      = 0,
			FarmLand        = 0,
			Farm            = 0,
			TrailerPark     = 0,
			TownZone        = 0,
			Nav             = 0,
		},
	},
	["ForestRarities"] = {
		chance = 1,
		name = "ForestRarities",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 8,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 1,
			Forest          = 1,
			Vegitation      = 0,
			FarmLand        = 0,
			Farm            = 0,
			TrailerPark     = 0,
			TownZone        = 0,
			Nav             = 0,
		},
	},
	["Insects"] = {
		chance = 10,
		name = "Insects",
		typeCategory = "Animals",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 5,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 30,
			Forest          = 25,
			Vegitation      = 25,
			FarmLand        = 15,
			Farm            = 15,
			TrailerPark     = 10,
			TownZone        = 10,
			Nav             = 10,
		},
		--spriteAffinities    = {
		--	"e_newgrass_1_0",
		--	"e_newgrass_1_1",
		--	"e_newgrass_1_2",
		--	"e_newgrass_1_3",
		--	"e_newgrass_1_4",
		--	"e_newgrass_1_5",
		--	"e_newgrass_1_6",
		--	"e_newgrass_1_7",
		--	"e_newgrass_1_8",
		--	"e_newgrass_1_9",
		--	"e_newgrass_1_10",
		--	"e_newgrass_1_11",
		--	"e_newgrass_1_12",
		--	"e_newgrass_1_13",
		--	"e_newgrass_1_14",
		--	"e_newgrass_1_15",
		--	"e_newgrass_1_16",
		--	"e_newgrass_1_17",
		--	"e_newgrass_1_18",
		--	"e_newgrass_1_19",
		--	"e_newgrass_1_20",
		--	"e_newgrass_1_21",
		--	"e_newgrass_1_22",
		--	"e_newgrass_1_23",
		--	"e_newgrass_1_24",
		--	"e_newgrass_1_25",
		--	"e_newgrass_1_26",
		--	"e_newgrass_1_27",
		--	"e_newgrass_1_28",
		--	"e_newgrass_1_29",
		--	"e_newgrass_1_30",
		--	"e_newgrass_1_31",
		--	"e_newgrass_1_32",
		--	"e_newgrass_1_33",
		--	"e_newgrass_1_34",
		--	"e_newgrass_1_35",
		--	"e_newgrass_1_36",
		--	"e_newgrass_1_37",
		--	"e_newgrass_1_38",
		--	"e_newgrass_1_39",
		--	"e_newgrass_1_40",
		--	"e_newgrass_1_41",
		--	"e_newgrass_1_42",
		--	"e_newgrass_1_43",
		--	"e_newgrass_1_44",
		--	"e_newgrass_1_45",
		--	"e_newgrass_1_46",
		--	"e_newgrass_1_47",
		--	"e_newgrass_1_48",
		--	"e_newgrass_1_49",
		--	"e_newgrass_1_50",
		--	"e_newgrass_1_51",
		--	"e_newgrass_1_52",
		--	"e_newgrass_1_53",
		--	"e_newgrass_1_54",
		--	"e_newgrass_1_55",
		--	"e_newgrass_1_56",
		--	"e_newgrass_1_57",
		--	"e_newgrass_1_58",
		--	"e_newgrass_1_59",
		--	"e_newgrass_1_60",
		--	"e_newgrass_1_61",
		--	"e_newgrass_1_62",
		--	"e_newgrass_1_63",
		--	"e_newgrass_1_64",
		--	"e_newgrass_1_65",
		--	"e_newgrass_1_66",
		--	"e_newgrass_1_67",
		--	"e_newgrass_1_68",
		--	"e_newgrass_1_69",
		--	"e_newgrass_1_70",
		--	"e_newgrass_1_71",
		--	"e_newgrass_1_72",
		--	"e_newgrass_1_73",
		--	"e_newgrass_1_74",
		--	"e_newgrass_1_75",
		--	"e_newgrass_1_76",
		--	"e_newgrass_1_77",
		--	"e_newgrass_1_78",
		--	"e_newgrass_1_79",
		--	"e_newgrass_1_80",
		--	"e_newgrass_1_81",
		--	"e_newgrass_1_82",
		--	"e_newgrass_1_83",
		--	"e_newgrass_1_84",
		--	"e_newgrass_1_85",
		--	"e_newgrass_1_86",
		--	"e_newgrass_1_87",
		--	"e_newgrass_1_88",
		--	"e_newgrass_1_89",
		--},
		--chanceToMoveIcon    = 1,
	},
	["MedicinalPlants"] = {
		chance = 30,
		name = "MedicinalPlants",
		typeCategory = "Medicinal",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 6,
		validFloors = { "floors_exterior_natural", "blends_natural" },
		zoneChance = {
			DeepForest      = 30,
			Forest          = 20,
			Vegitation      = 15,
			FarmLand        = 15,
			Farm            = 15,
			TrailerPark     = 3,
			TownZone        = 3,
			Nav             = 3,
		},
		--spriteAffinities    = {
		--	"d_generic_1_17",
		--	"d_generic_1_18",
		--	"d_generic_1_19",
		--	"d_generic_1_47",
		--	"d_generic_1_48",
		--	"d_generic_1_49",
		--	"d_generic_1_50",
		--	"d_generic_1_51",
		--	"d_generic_1_52",
		--	"d_generic_1_53",
		--	"d_generic_1_54",
		--	"d_generic_1_55",
		--	"d_generic_1_80",
		--	"d_generic_1_81",
		--	"d_generic_1_82",
		--	"d_generic_1_83",
		--	"d_generic_1_84",
		--	"d_generic_1_85",
		--	"d_generic_1_86",
		--	"d_generic_1_87",
		--},
		--chanceToMoveIcon    = 5,
	},
	["Firewood"] = {
		chance = 60,
		name = "Firewood",
		typeCategory = "Materials",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 1,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 250,
			Forest          = 200,
			Vegitation      = 75,
			FarmLand        = 35,
			Farm            = 35,
			TrailerPark     = 10,
			TownZone        = 10,
			Nav             = 15,
		},
		spriteAffinities    = {
			"d_generic_1_8",
			"d_generic_1_9",
			"d_generic_1_10",
			"d_generic_1_11",
			"d_generic_1_12",
			"d_generic_1_14",
			"d_generic_1_15",
			"d_generic_1_31",
			"d_generic_1_44",
			"d_generic_1_45",
		},
		chanceToMoveIcon    = 25,
	},
	["Stones"] = {
		chance = 40,
		name = "Stones",
		typeCategory = "Materials",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 1,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 25,
			Forest          = 25,
			Vegitation      = 30,
			FarmLand        = 30,
			Farm            = 30,
			TrailerPark     = 15,
			TownZone        = 15,
			Nav             = 80,
		},
		spriteAffinities    = {
			"d_generic_1_13",
			"d_generic_1_22",
			"d_generic_1_23",
			"d_generic_1_24",
			"d_generic_1_25",
			"d_generic_1_40",
			"d_generic_1_41",
			"d_generic_1_42",
			"d_generic_1_43",
		},
		chanceToMoveIcon    = 25,
	},
	["Junk"] = {
		chance = 10,
		name = "Junk",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 4,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 3,
			Forest          = 3,
			Vegitation      = 3,
			FarmLand        = 3,
			Farm            = 3,
			TrailerPark     = 7,
			TownZone        = 7,
			Nav             = 3,
		},
		spriteAffinities    = {
			"d_trash_0",
			"d_trash_1",
			"d_trash_2",
			"d_trash_3",
			"d_trash_4",
			"d_trash_5",
			"d_trash_6",
			"d_trash_7",
			"d_trash_8",
			"d_trash_9",
			"d_trash_10",
			"d_trash_11",
			"d_trash_12",
			"trash_01_0",
			"trash_01_1",
			"trash_01_2",
			"trash_01_3",
			"trash_01_4",
			"trash_01_5",
			"trash_01_6",
			"trash_01_7",
			"trash_01_8",
			"trash_01_9",
			"trash_01_10",
			"trash_01_11",
			"trash_01_12",
			"trash_01_16",
			"trash_01_17",
			"trash_01_18",
			"trash_01_19",
			"trash_01_20",
			"trash_01_21",
			"trash_01_22",
			"trash_01_23",
			"trash_01_24",
			"trash_01_25",
			"trash_01_26",
		},
		chanceToMoveIcon    = 20,
	},
	["JunkFood"] = {
		chance = 1,
		name = "JunkFood",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 4,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 1,
			Forest          = 1,
			Vegitation      = 1,
			FarmLand        = 3,
			Farm            = 3,
			TrailerPark     = 7,
			TownZone        = 7,
			Nav             = 1,
		},
	},
	["JunkWeapons"] = {
		chance = 1,
		name = "JunkWeapons",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 4,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 1,
			Forest          = 1,
			Vegitation      = 1,
			FarmLand        = 1,
			Farm            = 1,
			TrailerPark     = 5,
			TownZone        = 5,
			Nav             = 3,
		},
	},
	["Trash"] = {
		chance = 15,
		name = "Trash",
		typeCategory = "Other",
		showOptionPerk = "PlantScavenging",
		showCategoryLevel = 4,
		validFloors = { "ANY" },
		zoneChance = {
			DeepForest      = 5,
			Forest          = 5,
			Vegitation      = 10,
			FarmLand        = 5,
			Farm            = 5,
			TrailerPark     = 25,
			TownZone        = 25,
			Nav             = 25,
		},
		spriteAffinities    = {
			"d_trash_13",
			"d_trash_14",
			"d_trash_15",
			"d_trash_16",
			"d_trash_17",
			"d_trash_18",
			"d_trash_19",
			"d_trash_20",
			"d_trash_21",
			"d_trash_22",
			"d_trash_23",
			"d_trash_24",
			"d_trash_25",
			"trash_01_27",
			"trash_01_28",
			"trash_01_29",
			"trash_01_30",
			"trash_01_31",
			"trash_01_32",
			"trash_01_33",
			"trash_01_34",
			"trash_01_35",
			"trash_01_36",
			"trash_01_37",
			"trash_01_38",
			"trash_01_39",
			"trash_01_40",
			"trash_01_41",
			"trash_01_42",
			"trash_01_43",
			"trash_01_44",
			"trash_01_45",
			"trash_01_46",
			"trash_01_47",
			"trash_01_48",
			"trash_01_49",
			"trash_01_50",
			"trash_01_51",
			"trash_01_52",
			"trash_01_53",
		},
		chanceToMoveIcon    = 20,
	},
};

--[[--======== forageDefs ========--
]]--

forageDefs = {
	--======== BERRIES ========--
	--(added via generateBerryDefs)
	--======== FRUITS ========--
	Cherry = {
		type = "Base.Cherry",
		minCount = 1,
		maxCount = 4,
		skill = 4,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 5, 6, 7, 8, 9 },
		bonusMonths = { 6, 7, 8 },
		malusMonths = { 5, 9 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Strewberrie = {
		type = "farming.Strewberrie",
		skill = 8,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 4, 5, 6 },
		malusMonths = { 1, 2, 10, 11 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildstrawberry_worldSprite.png"),
		itemSizeModifier = 1.0,
	},
	Lemon = {
		type = "Base.Lemon",
		minCount = 1,
		maxCount = 3,
		skill = 6,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		bonusMonths = { 1, 2, 12 },
		malusMonths = { 3, 4, 10, 11 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Lime = {
		type = "Base.Lime",
		minCount = 1,
		maxCount = 3,
		skill = 6,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		bonusMonths = { 1, 2, 12 },
		malusMonths = { 3, 4, 10, 11 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Grapefruit = {
		type = "Base.Grapefruit",
		minCount = 1,
		maxCount = 1,
		skill = 8,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		bonusMonths = { 1, 2, 12 },
		malusMonths = { 3, 4, 10, 11 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Peach = {
		type = "Base.Peach",
		minCount = 1,
		maxCount = 2,
		skill = 8,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 4, 5, 6, 7, 8, 9, 10 },
		bonusMonths = { 6, 7, 8 },
		malusMonths = { 4, 5, 9, 10 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Pear = {
		type = "Base.Pear",
		minCount = 1,
		maxCount = 2,
		skill = 8,
		chance = 10,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 7, 8, 9, 10 },
		bonusMonths = { 8, 9 },
		malusMonths = { 7, 10 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	PepperHabanero = {
		type = "Base.PepperHabanero",
		minCount = 1,
		maxCount = 4,
		skill = 6,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 6, 7, 8, 9, 10 },
		bonusMonths = { 7, 8, 9 },
		malusMonths = { 6, 10 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	PepperJalapeno = {
		type = "Base.PepperJalapeno",
		minCount = 1,
		maxCount = 4,
		skill = 6,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 6, 7, 8, 9, 10 },
		bonusMonths = { 7, 8, 9 },
		malusMonths = { 6, 10 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Pineapple = {
		type = "Base.Pineapple",
		skill = 10,
		xp = 25,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			FarmLand    = 3,
			Farm        = 3,
		},
		months = { 2, 3, 4, 5, 6, 7, 8 },
		bonusMonths = { 4, 5, 6 },
		malusMonths = { 2, 8 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	Grapes = {
		type = "Base.Grapes",
		skill = 7,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = { 8, 9, 10 },
		malusMonths = { 6, 12 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	Orange = {
		type = "Base.Orange",
		minCount = 1,
		maxCount = 3,
		skill = 5,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 4, 5, 6, 7, 8, 9 },
		malusMonths = { 2, 11 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Apple = {
		type = "Base.Apple",
		minCount = 1,
		maxCount = 3,
		skill = 7,
		chance = 10,
		xp = 15,
		snowChance = -10,
		categories = { "Fruits" },
		zones = {
			Forest      = 10,
			FarmLand    = 15,
			Farm        = 15,
		},
		months = { 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = { 7, 8, 9, 10 },
		malusMonths = { 5, 12 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Banana = {
		type = "Base.Banana",
		minCount = 1,
		maxCount = 1,
		skill = 9,
		xp = 25,
		snowChance = -100,
		categories = { "Fruits" },
		zones = {
			Forest      = 1,
			FarmLand    = 3,
			Farm        = 3,
		},
		bonusMonths = { 3, 4, 5, 6, 7, 8, 9, 10 },
		malusMonths = { 1, 2, 11, 12 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Watermelon = {
		type = "Base.Watermelon",
		skill = 10,
		xp = 25,
		snowChance = -20,
		categories = { "Fruits" },
		zones = {
			Forest      = 1,
			FarmLand    = 3,
			Farm        = 3,
		},
		months = { 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = { 7, 8, 9, 10 },
		malusMonths = { 5, 12 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	--======== VEGETABLES ========--
	Onion = {
		type = "Base.Onion",
		skill = 3,
		xp = 15,
		snowChance = -10,
		categories = { "Vegetables" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 9 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	Lettuce = {
		type = "Base.Lettuce",
		skill = 7,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Vegitation  = 1,
			FarmLand    = 4,
			Farm        = 4,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	BellPepper = {
		type = "Base.BellPepper",
		skill = 7,
		xp = 15,
		snowChance = -20,
		categories = { "Vegetables" },
		zones = {
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Avocado = {
		type = "Base.Avocado",
		skill = 8,
		xp = 15,
		snowChance = -50,
		categories = { "Vegetables" },
		zones = {
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.smallTrees,
		itemSizeModifier = 1.5,
	},
	Zucchini = {
		type = "Base.Zucchini",
		skill = 8,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.shrubs,
	},
	Corn = {
		type = "Base.Corn",
		skill = 8,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Vegitation  = 1,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/corn_worldSprite.png"),
		itemSizeModifier = 1.5,
	},
	Eggplant = {
		type = "Base.Eggplant",
		skill = 8,
		xp = 15,
		snowChance = -50,
		categories = { "Vegetables" },
		zones = {
			FarmLand    = 3,
			Farm        = 3,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.shrubs,
	},
	Leek = {
		type = "Base.Leek",
		skill = 2,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 10,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 9 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	--======== CROPS  ========--
	Carrots = {
		type = "Base.Carrots",
		skill = 2,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Forest      = 7,
			Vegitation  = 7,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = { getTexture("media/textures/Foraging/worldSprites/wildcarrot_worldSprite.png") },
	},
	Broccoli = {
		type = "farming.BloomingBroccoli",
		skill = 2,
		chance = 15,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Forest      = 7,
			Vegitation  = 7,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = worldSprites.shrubs,
	},
	Potato = {
		type = "farming.Potato",
		skill = 2,
		xp = 15,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Forest      = 7,
			Vegitation  = 7,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildpotato_worldSprite.png"),
	},
	Cabbage = {
		type = "farming.Cabbage",
		skill = 2,
		xp = 15,
		snowChance = -10,
		categories = { "Vegetables" },
		zones = {
			Forest      = 3,
			Vegitation  = 3,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildcabbage_worldSprite.png"),
	},
	Tomato = {
		type = "farming.Tomato",
		skill = 2,
		xp = 15,
		snowChance = -10,
		categories = { "Vegetables" },
		zones = {
			Forest      = 3,
			Vegitation  = 3,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildtomato_worldSprite.png"),
	},
	RedRadish = {
		type = "farming.RedRadish",
		skill = 2,
		xp = 15,
		snowChance = -10,
		categories = { "Vegetables" },
		zones = {
			Forest      = 3,
			Vegitation  = 3,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn, doWildCropSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	Daikon = {
		type = "Base.Daikon",
		skill = 5,
		chance = 5,
		xp = 15,
		snowChance = -10,
		categories = { "Vegetables" },
		zones = {
			Vegitation  = 1,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	Peanuts = {
		type = "Base.Peanuts",
		skill = 7,
		xp = 25,
		snowChance = -30,
		categories = { "Vegetables" },
		zones = {
			Forest      = 3,
			DeepForest  = 3,
			Vegitation  = 3,
			FarmLand    = 3,
			Farm        = 3,
		},
		months = { 9, 10, 11 },
		bonusMonths = { 10 },
		malusMonths = { 11 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	--======== MUSHROOMS ========--
	--(added via generateMushroomDefs)
	--======== MEDICINAL PLANTS ========--
	Violets = {
		type = "Base.Violets",
		minCount = 2,
		maxCount = 5,
		xp = 15,
		rainChance = 10,
		snowChance = -10,
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = { {"d_plants_1_40"}, {"d_plants_1_41"}, {"d_plants_1_44"} },
		doIsoMarkerObject = true,
	},
	GrapeLeaves = {
		type = "Base.GrapeLeaves",
		minCount = 1,
		maxCount = 5,
		skill = 2,
		xp = 15,
		rainChance = 10,
		snowChance = -10,
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	Rosehips = {
		type = "Base.Rosehips",
		minCount = 1,
		maxCount = 4,
		skill = 4,
		xp = 15,
		rainChance = 10,
		snowChance = -10,
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 10,
			Farm        = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.shrubs,
	},
	Plantain = {
		type = "Base.Plantain",
		minCount = 2,
		maxCount = 5,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 7, 8, 9 },
		malusMonths = { 3, 4 },
		altWorldTexture = worldSprites.wildPlants,
	},
	Comfrey = {
		type = "Base.Comfrey",
		minCount = 2,
		maxCount = 5,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		altWorldTexture = worldSprites.vines,
	},
	WildGarlic = {
		type = "Base.WildGarlic",
		minCount = 2,
		maxCount = 5,
		xp = 15,
		rainChance = 50,
		snowChance = -20,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		altWorldTexture = worldSprites.wildPlants,
	},
	CommonMallow = {
		type = "Base.CommonMallow",
		minCount = 2,
		maxCount = 5,
		chance = 20,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.vines,
	},
	LemonGrass = {
		type = "Base.LemonGrass",
		minCount = 2,
		maxCount = 5,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 5, 6, 7 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = getTexture("media/textures/Foraging/worldSprites/lemongrass_worldSprite.png"),
	},
	BlackSage = {
		type = "Base.BlackSage",
		minCount = 1,
		maxCount = 3,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 7, 8, 9 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	Ginseng = {
		type = "Base.Ginseng",
		minCount = 1,
		maxCount = 3,
		xp = 15,
		rainChance = 50,
		snowChance = -10,
		traits = { "Herbalist" },
		categories = { "MedicinalPlants" },
		zones = {
			Forest      = 10,
			DeepForest  = 15,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		bonusMonths = { 7, 8, 9 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
		altWorldTexture = worldSprites.wildPlants,
	},
	--======== ANIMALS ========--
	WildEggs = {
		type = "Base.WildEggs",
		minCount = 1,
		maxCount = 3,
		skill = 8,
		xp = 20,
		rainChance = -20,
		snowChance = -20,
		categories = { "Animals" },
		zones = {
			Forest      = 5,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
	},
	Egg = {
		type = "Base.Egg",
		minCount = 1,
		maxCount = 3,
		skill = 8,
		xp = 20,
		rainChance = -20,
		snowChance = -20,
		categories = { "Animals" },
		zones = {
			Forest      = 5,
			DeepForest  = 10,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doWildFoodSpawn },
	},
	Worm = {
		type = "Base.Worm",
		minCount = 1,
		maxCount = 2,
		skill = 2,
		chance = 5,
		rainChance = 100,
		snowChance = -100,
		--itemTags = { "DigPlow" },
		categories = { "FishBait" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
	},
	Frog = {
		type = "Base.Frog",
		skill = 7,
		xp = 20,
		rainChance = 100,
		snowChance = -100,
		categories = { "Animals" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 2,
			Farm        = 2,
			TrailerPark = 1,
			TownZone    = 1,
			Nav         = 0,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
	},
	--======== DEAD ANIMALS ========--
	DeadBird = {
		type = "Base.DeadBird",
		skill = 7,
		chance = 2,
		xp = 20,
		rainChance = -10,
		snowChance = -10,
		categories = { "Animals" },
		zones = {
			Forest      = 2,
			DeepForest  = 2,
			Vegitation  = 2,
			FarmLand    = 2,
			Farm        = 2,
			TrailerPark = 2,
			TownZone    = 2,
			Nav         = 2,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doDeadTrapAnimalSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	DeadSquirrel = {
		type = "Base.DeadSquirrel",
		skill = 8,
		xp = 20,
		rainChance = -10,
		snowChance = -10,
		categories = { "Animals" },
		zones = {
			Forest      = 2,
			DeepForest  = 2,
			Vegitation  = 2,
			FarmLand    = 2,
			Farm        = 2,
			TrailerPark = 2,
			TownZone    = 2,
			Nav         = 2,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doDeadTrapAnimalSpawn },
	},
	DeadRabbit = {
		type = "Base.DeadRabbit",
		skill = 10,
		xp = 20,
		rainChance = -10,
		snowChance = -10,
		categories = { "Animals" },
		zones = {
			Forest      = 2,
			DeepForest  = 2,
			Vegitation  = 2,
			FarmLand    = 2,
			Farm        = 2,
			TrailerPark = 0,
			TownZone    = 0,
			Nav         = 2,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doDeadTrapAnimalSpawn },
	},
	DeadRat = {
		type = "Base.DeadRat",
		skill = 5,
		xp = 20,
		rainChance = -10,
		snowChance = -10,
		categories = { "Animals" },
		zones = {
			Forest      = 2,
			DeepForest  = 2,
			Vegitation  = 2,
			FarmLand    = 2,
			Farm        = 2,
			TrailerPark = 2,
			TownZone    = 2,
			Nav         = 2,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		spawnFuncs = { doDeadTrapAnimalSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	--======== INSECTS ========--
	Cricket = {
		type = "Base.Cricket",
		skill = 0,
		rainChance = 30,
		snowChance = -30,
		categories = { "Insects", "FishBait" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 10,
			FarmLand    = 10,
			Farm        = 10,
			TrailerPark = 10,
			TownZone    = 10,
			Nav         = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	Grasshopper = {
		type = "Base.Grasshopper",
		skill = 0,
		rainChance = 20,
		snowChance = -30,
		categories = { "Insects", "FishBait" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 10,
			FarmLand    = 10,
			Farm        = 10,
			TrailerPark = 10,
			TownZone    = 10,
			Nav         = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	Cockroach = {
		type = "Base.Cockroach",
		skill = 0,
		rainChance = 10,
		snowChance = -20,
		categories = { "Insects", "FishBait" },
		zones = {
			Forest      = 10,
			DeepForest  = 10,
			Vegitation  = 10,
			FarmLand    = 10,
			Farm        = 10,
			TrailerPark = 10,
			TownZone    = 10,
			Nav         = 10,
		},
		months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
		malusMonths = { 3, 4 },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	--======== FOREST GOODS ========--
	Log = {
		type = "Base.Log",
		skill = 3,
		categories = { "Firewood" },
		zones = {
			DeepForest  = 3,
			Forest      = 2,
			Vegitation  = 1,
		},
		bonusMonths = { 9, 10, 11 },
	},
	TreeBranch = {
		type = "Base.TreeBranch",
		minCount = 1,
		maxCount = 2,
		xp = 15,
		categories = { "Firewood" },
		zones = {
			DeepForest  = 5,
			Forest      = 4,
			Vegitation  = 4,
			FarmLand    = 3,
			Farm        = 3,
			TrailerPark = 2,
			TownZone    = 2,
			Nav         = 1,
		},
		bonusMonths = { 9, 10, 11 },
	},
	Twigs = {
		type = "Base.Twigs",
		minCount = 1,
		maxCount = 3,
		categories = { "Firewood" },
		zones = {
			Forest      = 9,
			DeepForest  = 9,
			Vegitation  = 9,
			FarmLand    = 7,
			Farm        = 7,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
		},
		bonusMonths = { 9, 10, 11 },
	},
	SharpedStone = {
		type = "Base.SharpedStone",
		snowChance = -10,
		categories = { "Stones" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
		},
	},
	Stone = {
		type = "Base.Stone",
		snowChance = -10,
		categories = { "Stones" },
		zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
		},
		months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
	},
	--======== FOREST RARITIES ========--
	CampfireKit = {
		type = "camping.CampfireKit",
		skill = 2,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	CampingTentKit = {
		type = "camping.CampingTentKit",
		skill = 5,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	HottieZ = {
		type = "Base.HottieZ",
		skill = 10,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Tarp = {
		type = "Base.Tarp",
		skill = 4,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 5,
		},
	},
	TentPeg = {
		type = "camping.TentPeg",
		minCount = 1,
		maxCount = 4,
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 10,
		},
	},
	TrapBox = {
		type = "Base.TrapBox",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	TrapCage = {
		type = "Base.TrapCage",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	TrapCrate = {
		type = "Base.TrapCrate",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	TrapMouse = {
		type = "Base.TrapMouse",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	TrapSnare = {
		type = "Base.TrapSnare",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	TrapStick = {
		type = "Base.TrapStick",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Bag_NormalHikingBag = {
		type = "Base.Bag_NormalHikingBag",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Bag_BigHikingBag = {
		type = "Base.Bag_BigHikingBag",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Bag_SurvivorBag = {
		type = "Base.Bag_SurvivorBag",
		skill = 8,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Bag_ALICEpack = {
		type = "Base.Bag_ALICEpack",
		skill = 10,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	Bag_ALICEpack_Army = {
		type = "Base.Bag_ALICEpack_Army",
		skill = 10,
		xp = 25,
		categories = { "ForestRarities" },
		zones = {
			DeepForest  = 1,
		},
	},
	--======== TRASH ITEMS ========--
	--(added via generateJunkDefs)
	--======== JUNK ITEMS ========--
	--(added via generateJunkDefs)
};
-------------------------------------------------
-------------------------------------------------
local function generateBerryDefs()
	local items = {
		generic = {
			chance = 15,
			poisonChance = 5,
			poisonPowerMin = 10,
			poisonPowerMax = 30,
			poisonDetectionLevel = 7,
			spawnFuncs = { doPoisonItemSpawn, doWildFoodSpawn },
			items = {
				BerryGeneric5 = "Base.BerryGeneric5",
				BerryGeneric4 = "Base.BerryGeneric4",
				BerryGeneric3 = "Base.BerryGeneric3",
				BerryGeneric2 = "Base.BerryGeneric2",
				BerryGeneric1 = "Base.BerryGeneric1",
				BerryPoisonIvy = "Base.BerryPoisonIvy",
			},
		},
		specific = {
			chance = 10,
			poisonChance = 0,
			poisonPowerMin = 0,
			poisonPowerMax = 0,
			poisonDetectionLevel = 0,
			spawnFuncs = { doWildFoodSpawn },
			items = {
				BerryBlack = "Base.BerryBlack",
				BerryBlue = "Base.BerryBlue",
			},
		},
	};
	for _, spawnTable in pairs(items) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageDefs[itemName] = {
				type = itemFullName,
				minCount = 1,
				maxCount = 4,
				xp = 20,
				snowChance = -10,
				categories = { "Berries" },
				zones = {
					Forest      = spawnTable.chance,
					DeepForest  = spawnTable.chance,
					Vegitation  = spawnTable.chance,
					FarmLand    = spawnTable.chance,
					Farm        = spawnTable.chance,
				},
				months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
				bonusMonths = { 5, 6, 7 },
				malusMonths = { 3, 4 },
				spawnFuncs = spawnTable.spawnFuncs,
				poisonChance = spawnTable.poisonChance,
				poisonPowerMin = spawnTable.poisonPowerMin,
				poisonPowerMax = spawnTable.poisonPowerMax,
				poisonDetectionLevel = spawnTable.poisonDetectionLevel,
				altWorldTexture = worldSprites.berryBushes,
				doIsoMarkerObject = true,
				itemSizeModifier = 1.0,
			};
		end;
	end;
end

generateBerryDefs();
-------------------------------------------------
-------------------------------------------------
local function generateMushroomDefs()
	local items = {
		generic = {
			chance = 15,
			poisonChance = 10,
			poisonPowerMin = 15,
			poisonPowerMax = 75,
			poisonDetectionLevel = 7,
			spawnFuncs = { doPoisonItemSpawn, doWildFoodSpawn },
			items = {
				MushroomGeneric7 = "Base.MushroomGeneric7",
				MushroomGeneric6 = "Base.MushroomGeneric6",
				MushroomGeneric5 = "Base.MushroomGeneric5",
				MushroomGeneric4 = "Base.MushroomGeneric4",
				MushroomGeneric3 = "Base.MushroomGeneric3",
				MushroomGeneric2 = "Base.MushroomGeneric2",
				MushroomGeneric1 = "Base.MushroomGeneric1",
			},
		},
	};
	for _, spawnTable in pairs(items) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageDefs[itemName] = {
				type = itemFullName,
				minCount = 1,
				maxCount = 3,
				xp = 20,
				rainChance = 15,
				categories = { "Mushrooms" },
				zones = {
					Forest      = spawnTable.chance,
					DeepForest  = spawnTable.chance,
					Vegitation  = spawnTable.chance,
					FarmLand    = spawnTable.chance,
					Farm        = spawnTable.chance,
					TrailerPark = spawnTable.chance,
					TownZone    = spawnTable.chance,
					Nav         = spawnTable.chance,
				},
				months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
				bonusMonths = { 8, 9, 10 },
				malusMonths = { 3, 4 },
				spawnFuncs = spawnTable.spawnFuncs,
				poisonChance = spawnTable.poisonChance,
				poisonPowerMin = spawnTable.poisonPowerMin,
				poisonPowerMax = spawnTable.poisonPowerMax,
				poisonDetectionLevel = spawnTable.poisonDetectionLevel,
			};
		end;
	end;
end

generateMushroomDefs();
-------------------------------------------------
-------------------------------------------------
local function generateJunkDefs()
	local junkWeapons = {
		normal = {
			chance = 50,
			xp = 10,
			items = {
				BluePen       = "Base.BluePen",
				Pen           = "Base.Pen",
				Pencil        = "Base.Pencil",
				RedPen        = "Base.RedPen",
				SmashedBottle = "Base.SmashedBottle",
				BreadKnife    = "Base.BreadKnife",
				ButterKnife   = "Base.ButterKnife",
				Fork          = "Base.Fork",
				Scissors      = "Base.Scissors",
				Spoon         = "Base.Spoon",
				KitchenKnife  = "Base.KitchenKnife",
			},
		},
		uncommon = {
			chance = 25,
			xp = 15,
			items = {
				BallPeenHammer    = "Base.BallPeenHammer",
				ChairLeg          = "Base.ChairLeg",
				CraftedFishingRod = "Base.CraftedFishingRod",
				Drumstick         = "Base.Drumstick",
				IcePick           = "Base.IcePick",
				LeadPipe          = "Base.LeadPipe",
				Pan               = "Base.Pan",
				Plank             = "Base.Plank",
				PlankNail         = "Base.PlankNail",
				Plunger           = "Base.Plunger",
				Poolcue           = "Base.Poolcue",
				RollingPin        = "Base.RollingPin",
				Saucepan          = "Base.Saucepan",
				Rake              = "Base.Rake",
				Shovel            = "Base.Shovel",
				Shovel2           = "Base.Shovel2",
				SnowShovel        = "Base.SnowShovel",
			},
		},
		rare = {
			chance = 15,
			xp = 25,
			items = {
				BadmintonRacket     = "Base.BadmintonRacket",
				Broom               = "Base.Broom",
				FlintKnife          = "Base.FlintKnife",
				ClosedUmbrellaBlack = "Base.ClosedUmbrellaBlack",
				ClosedUmbrellaBlue  = "Base.ClosedUmbrellaBlue",
				ClosedUmbrellaRed   = "Base.ClosedUmbrellaRed",
				ClosedUmbrellaWhite = "Base.ClosedUmbrellaWhite",
				GardenFork          = "Base.GardenFork",
				GardenHoe           = "Base.GardenHoe",
				Golfclub            = "Base.Golfclub",
				GridlePan           = "Base.GridlePan",
				Hammer              = "Base.Hammer",
				HuntingKnife        = "Base.HuntingKnife",
				LetterOpener        = "Base.LetterOpener",
				Machete             = "Base.Machete",
				MeatCleaver         = "Base.MeatCleaver",
				MetalBar            = "Base.MetalBar",
				MetalPipe           = "Base.MetalPipe",
				Nightstick          = "Base.Nightstick",
				PickAxe             = "Base.PickAxe",
				PickAxeHandle       = "Base.PickAxeHandle",
				PickAxeHandleSpiked = "Base.PickAxeHandleSpiked",
				PipeWrench          = "Base.PipeWrench",
				Screwdriver         = "Base.Screwdriver",
				Stake               = "Base.Stake",
				TableLeg            = "Base.TableLeg",
			},
		},
		epic = {
			chance = 5,
			xp = 50,
			items = {
				BaseballBat         = "Base.BaseballBat",
				Banjo               = "Base.Banjo",
				ClubHammer          = "Base.ClubHammer",
				Crowbar             = "Base.Crowbar",
				FishingRod          = "Base.FishingRod",
				HandAxe             = "Base.HandAxe",
				HandFork            = "Base.HandFork",
				HandScythe          = "Base.HandScythe",
				HockeyStick         = "Base.HockeyStick",
				IceHockeyStick      = "Base.IceHockeyStick",
				TennisRacket        = "Base.TennisRacket",
			},
		},
		legendary = {
			chance = 1,
			xp = 100,
			items = {
				AssaultRifle               = "Base.AssaultRifle",
				AssaultRifle2              = "Base.AssaultRifle2",
				Axe                        = "Base.Axe",
				DoubleBarrelShotgun        = "Base.DoubleBarrelShotgun",
				DoubleBarrelShotgunSawnoff = "Base.DoubleBarrelShotgunSawnoff",
				HuntingRifle               = "Base.HuntingRifle",
				Katana                     = "Base.Katana",
				Pistol                     = "Base.Pistol",
				Pistol2                    = "Base.Pistol2",
				Pistol3                    = "Base.Pistol3",
				Revolver                   = "Base.Revolver",
				Revolver_Long              = "Base.Revolver_Long",
				Revolver_Short             = "Base.Revolver_Short",
				Shotgun                    = "Base.Shotgun",
				ShotgunSawnoff             = "Base.ShotgunSawnoff",
				VarmintRifle               = "Base.VarmintRifle",
				WoodAxe                    = "Base.WoodAxe",
			},
		},
	};
	for _, spawnTable in pairs(junkWeapons) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageDefs[itemName] = {
				type = itemFullName,
				skill = 5,
				xp = spawnTable.xp,
				categories = { "JunkWeapons" },
				zones = {
					DeepForest  = spawnTable.chance,
					Forest      = spawnTable.chance,
					Vegitation  = spawnTable.chance,
					FarmLand    = spawnTable.chance,
					Farm        = spawnTable.chance,
					TrailerPark = spawnTable.chance,
					TownZone    = spawnTable.chance,
					Nav         = spawnTable.chance,
				},
				spawnFuncs = { doJunkWeaponSpawn },
				forceOutside = false,
				canBeAboveFloor = true,
				itemSizeModifier = 1.0,
				isItemOverrideSize = true,
			};
		end;
	end;
	local junkItems = {
		normal = {
			chance = 100,
			xp = 10,
			items = {
				Nails         = "Base.Nails",
				Screws        = "Base.Screws",
				ScrapMetal    = "Base.ScrapMetal",
				UnusableWood  = "Base.UnusableWood",
				UnusableMetal = "Base.UnusableMetal",
				Crayons       = "Base.Crayons",
				Notebook      = "Base.Notebook",
				Journal       = "Base.Journal",
				Magazine      = "Base.Magazine",
			},
		},
		common = {
			chance = 50,
			xp = 25,
			items = {
				Book         = "Base.Book",
				ComicBook    = "Base.ComicBook",
				Paperclip    = "Base.Paperclip",
				PaperclipBox = "Base.PaperclipBox",
				ScrewsBox    = "Base.ScrewsBox",
				SheetMetal   = "Base.SheetMetal",
				Bowl         = "Base.Bowl",
				Pot          = "Base.Pot",
				Hinge        = "Base.Hinge",
			},
		},
		uncommon = {
			chance = 33,
			xp = 25,
			items = {
				Saw                     = "Base.Saw",
				Tote                    = "Base.Tote",
				EmptySandbag            = "Base.EmptySandbag",
				Purse                   = "Base.Purse",
				Suitcase                = "Base.Suitcase",
				Handbag                 = "Base.Handbag",
				Toolbox                 = "Base.Toolbox",
				FirstAidKit             = "Base.FirstAidKit",
				Lunchbox                = "Base.Lunchbox",
				Lunchbox2               = "Base.Lunchbox2",
				Bag_Satchel             = "Base.Bag_Satchel",
				Cooler                  = "Base.Cooler",
				Cigarettes              = "Base.Cigarettes",
				Lighter                 = "Base.Lighter",
				Matches                 = "Base.Matches",
				BlowTorch               = "Base.BlowTorch",
				Eraser                  = "Base.Eraser",
				FishingNet              = "Base.FishingNet",
				FishingTackle           = "Base.FishingTackle",
				FishingTackle2          = "Base.FishingTackle2",
			},
		},
		unlikely = {
			chance = 20,
			xp = 50,
			items = {
				Bag_GolfBag             = "Base.Bag_GolfBag",
				Bag_Schoolbag           = "Base.Bag_Schoolbag",
				Bag_BowlingBallBag      = "Base.Bag_BowlingBallBag",
				Flightcase              = "Base.Flightcase",
				Guitarcase              = "Base.Guitarcase",
				CookingMag1             = "Base.CookingMag1",
				CookingMag2             = "Base.CookingMag2",
				ElectronicsMag1         = "Base.ElectronicsMag1",
				ElectronicsMag2         = "Base.ElectronicsMag2",
				ElectronicsMag3         = "Base.ElectronicsMag3",
				ElectronicsMag4         = "Base.ElectronicsMag4",
				ElectronicsMag5         = "Base.ElectronicsMag5",
				EngineerMagazine1       = "Base.EngineerMagazine1",
				EngineerMagazine2       = "Base.EngineerMagazine2",
				FarmingMag1             = "Base.FarmingMag1",
				FishingLine             = "Base.FishingLine",
				FishingMag1             = "Base.FishingMag1",
				FishingMag2             = "Base.FishingMag2",
				HuntingMag1             = "Base.HuntingMag1",
				HuntingMag2             = "Base.HuntingMag2",
				HuntingMag3             = "Base.HuntingMag3",
				MarchRidgeMap           = "Base.MarchRidgeMap",
				MetalworkMag1           = "Base.MetalworkMag1",
				MetalworkMag2           = "Base.MetalworkMag2",
				MetalworkMag3           = "Base.MetalworkMag3",
				MetalworkMag4           = "Base.MetalworkMag4",
				MuldraughMap            = "Base.MuldraughMap",
				RiversideMap            = "Base.RiversideMap",
				RosewoodMap             = "Base.RosewoodMap",
				SewingKit               = "Base.SewingKit",
				UmbrellaBlack           = "Base.UmbrellaBlack",
				UmbrellaBlue            = "Base.UmbrellaBlue",
				UmbrellaRed             = "Base.UmbrellaRed",
				UmbrellaWhite           = "Base.UmbrellaWhite",
				WestpointMap            = "Base.WestpointMap",
			},
		},
		rare = {
			chance = 15,
			xp = 50,
			items = {
				PetrolCan               = "Base.PetrolCan",
				PropaneTank             = "Base.PropaneTank",
				Charcoal                = "Base.Charcoal",
			},
		},
		epic = {
			chance = 5,
			xp = 75,
			items = {
				["223Box"]           = "Base.223Box",
				["223Clip"]          = "Base.223Clip",
				["308Box"]           = "Base.308Box",
				["308Clip"]          = "Base.308Clip",
				["44Clip"]           = "Base.44Clip",
				["45Clip"]           = "Base.45Clip",
				["556Box"]           = "Base.556Box",
				["556Clip"]          = "Base.556Clip",
				["9mmClip"]          = "Base.9mmClip",
				["Bullets38Box"]     = "Base.Bullets38Box",
				["Bullets44Box"]     = "Base.Bullets44Box",
				["Bullets45Box"]     = "Base.Bullets45Box",
				["Bullets9mmBox"]    = "Base.Bullets9mmBox",
				["M14Clip"]          = "Base.M14Clip",
				["ShotgunShellsBox"] = "Base.ShotgunShellsBox",
			},
		},
		legendary = {
			chance = 1,
			xp = 100,
			items = {
				PipeBomb          = "Base.PipeBomb",
				AmmoStraps        = "Base.AmmoStraps",
				Bayonnet          = "Base.Bayonnet",
				ChokeTubeFull     = "Base.ChokeTubeFull",
				ChokeTubeImproved = "Base.ChokeTubeImproved",
				FiberglassStock   = "Base.FiberglassStock",
				GunLight          = "Base.GunLight",
				IronSight         = "Base.IronSight",
				Sling             = "Base.Sling",
				x2Scope           = "Base.x2Scope",
				x4Scope           = "Base.x4Scope",
				x8Scope           = "Base.x8Scope",
				HerbalistMag      = "Base.HerbalistMag",
			},
		},
	};
	for _, spawnTable in pairs(junkItems) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageDefs[itemName] = {
				type = itemFullName,
				skill = 4,
				xp = spawnTable.xp,
				categories = { "Junk" },
				zones = {
					Forest      = spawnTable.chance,
					DeepForest  = spawnTable.chance,
					Vegitation  = spawnTable.chance,
					FarmLand    = spawnTable.chance,
					Farm        = spawnTable.chance,
					TrailerPark = spawnTable.chance,
					TownZone    = spawnTable.chance,
					Nav         = spawnTable.chance,
				},
				spawnFuncs = { doJunkWeaponSpawn },
				forceOutside = false,
				canBeAboveFloor = true,
				itemSizeModifier = 1.0,
				isItemOverrideSize = true,
			};
		end;
	end;
	local junkFood = {
		BeerBottle         = "Base.BeerBottle",
		BeerCan            = "Base.BeerCan",
		Bleach             = "Base.Bleach",
		CandyPackage       = "Base.CandyPackage",
		Candycane          = "Base.Candycane",
		CannedBellPepper   = "Base.CannedBellPepper",
		CannedBolognese    = "Base.CannedBolognese",
		CannedBroccoli     = "Base.CannedBroccoli",
		CannedCabbage      = "Base.CannedCabbage",
		CannedCarrots      = "Base.CannedCarrots",
		CannedCarrots2     = "Base.CannedCarrots2",
		CannedChili        = "Base.CannedChili",
		CannedCorn         = "Base.CannedCorn",
		CannedCornedBeef   = "Base.CannedCornedBeef",
		CannedEggplant     = "Base.CannedEggplant",
		CannedLeek         = "Base.CannedLeek",
		CannedMushroomSoup = "Base.CannedMushroomSoup",
		CannedPeas         = "Base.CannedPeas",
		CannedPotato       = "Base.CannedPotato",
		CannedPotato2      = "Base.CannedPotato2",
		CannedRedRadish    = "Base.CannedRedRadish",
		CannedSardines     = "Base.CannedSardines",
		CannedTomato       = "Base.CannedTomato",
		CannedTomato2      = "Base.CannedTomato2",
		Cereal             = "Base.Cereal",
		Chocolate          = "Base.Chocolate",
		Chocolate          = "Base.Chocolate",
		Coffee2            = "Base.Coffee2",
		Crisps             = "Base.Crisps",
		Crisps2            = "Base.Crisps2",
		Crisps3            = "Base.Crisps3",
		Crisps4            = "Base.Crisps4",
		Cupcake            = "Base.Cupcake",
		Dogfood            = "Base.Dogfood",
		GranolaBar         = "Base.GranolaBar",
		Gum                = "Base.Gum",
		Honey              = "Base.Honey",
		JamFruit           = "Base.JamFruit",
		JamMarmalade       = "Base.JamMarmalade",
		JuiceBox           = "Base.JuiceBox",
		Lollipop           = "Base.Lollipop",
		MintCandy          = "Base.MintCandy",
		PeanutButter       = "Base.PeanutButter",
		Pop                = "Base.Pop",
		Pop2               = "Base.Pop2",
		Pop3               = "Base.Pop3",
		PopBottle          = "Base.PopBottle",
		Popcorn            = "Base.Popcorn",
		RiceVinegar        = "Base.RiceVinegar",
		Soysauce           = "Base.Soysauce",
		SugarBrown         = "Base.SugarBrown",
		Teabag2            = "Base.Teabag2",
		TinnedSoup         = "Base.TinnedSoup",
		TunaTin            = "Base.TunaTin",
		WaterBottleFull    = "Base.WaterBottleFull",
		WhiskeyFull        = "Base.WhiskeyFull",
		WhiskeyWaterFull   = "Base.WhiskeyWaterFull",
		Wine               = "Base.Wine",
		Wine2              = "Base.Wine2",
	};
	for itemName, itemFullName in pairs(junkFood) do
		forageDefs[itemName] = {
			type = itemFullName,
			xp = 25,
			categories = { "JunkFood" },
			zones = {
				TrailerPark = 5,
				TownZone    = 5,
				Nav         = 1,
			},
			forceOutside = false,
			canBeAboveFloor = true,
		};
	end;
	local trashItems = {
		normal = {
			chance = 100,
			xp = 10,
			items = {
				BeerCanEmpty        = "Base.BeerCanEmpty",
				BeerEmpty           = "Base.BeerEmpty",
				Newspaper           = "Base.Newspaper",
				Pop2Empty           = "Base.Pop2Empty",
				Pop3Empty           = "Base.Pop3Empty",
				PopEmpty            = "Base.PopEmpty",
				SheetPaper2         = "Base.SheetPaper2",
				SmashedBottle       = "Base.SmashedBottle",
				TinCanEmpty         = "Base.TinCanEmpty",
				WaterBottleEmpty    = "Base.WaterBottleEmpty",
				Garbagebag          = "Base.Garbagebag",
				Plasticbag          = "Base.Plasticbag",
			},
		},
		uncommon = {
			chance = 50,
			xp = 25,
			items = {
				Aluminum           = "Base.Aluminum",
				Baseball           = "Base.Baseball",
				Basketball         = "Base.Basketball",
				Bell               = "Base.Bell",
				BleachEmpty        = "Base.BleachEmpty",
				Bricktoys          = "Base.Bricktoys",
				BrokenFishingNet   = "Base.BrokenFishingNet",
				CarvingFork        = "Base.CarvingFork",
				CatToy             = "Base.CatToy",
				Chopsticks         = "Base.Chopsticks",
				Coldpack           = "Base.Coldpack",
				Cologne            = "Base.Cologne",
				Comb               = "Base.Comb",
				Corkscrew          = "Base.Corkscrew",
				DenimStripsDirty   = "Base.DenimStripsDirty",
				DuctTape           = "Base.DuctTape",
				FountainCup        = "Base.FountainCup",
				GlassTumbler       = "Base.GlassTumbler",
				GlassWine          = "Base.GlassWine",
				Glue               = "Base.Glue",
				GrillBrush         = "Base.GrillBrush",
				Hairgel            = "Base.Hairgel",
				LeatherStripsDirty = "Base.LeatherStripsDirty",
				Money              = "Base.Money",
				MuffinTray         = "Base.MuffinTray",
				OvenMitt           = "Base.OvenMitt",
				PaintbucketEmpty   = "Base.PaintbucketEmpty",
				PlasticCup         = "Base.PlasticCup",
				PlasticTray        = "Base.PlasticTray",
				Plate              = "Base.Plate",
				PlateBlue          = "Base.PlateBlue",
				PlateBlue          = "Base.PlateBlue",
				PlateFancy         = "Base.PlateFancy",
				PlateOrange        = "Base.PlateOrange",
				PopBottleEmpty     = "Base.PopBottleEmpty",
				Scotchtape         = "Base.Scotchtape",
				Spatula            = "Base.Spatula",
				Straw              = "Base.Straw",
				Teacup             = "Base.Teacup",
				Tongs              = "Base.Tongs",
				WeldingRods        = "Base.WeldingRods",
				WhiskeyEmpty       = "Base.WhiskeyEmpty",
				WineEmpty          = "Base.WineEmpty",
				WineEmpty2         = "Base.WineEmpty2",
				WoodGlue           = "Base.Woodglue",
			},
		},
		rare = {
			chance = 15,
			xp = 50,
			items = {
				CreditCard       = "Base.CreditCard",
				Cube             = "Base.Cube",
				Dart             = "Base.Dart",
				Dice             = "Base.Dice",
				DogChew          = "Base.DogChew",
				Doll             = "Base.Doll",
				FertilizerEmpty  = "Base.FertilizerEmpty",
				Football         = "Base.Football",
				Football2        = "Base.Football2",
				GolfBall         = "Base.GolfBall",
				HandTorch        = "Base.HandTorch",
				KatePic          = "Base.KatePic",
				KnittingNeedles  = "Base.KnittingNeedles",
				Leash            = "Base.Leash",
				Lighter          = "Base.Lighter",
				Locket           = "Base.Locket",
				Matches          = "Base.Matches",
				Mirror           = "Base.Mirror",
				Perfume          = "Base.Perfume",
				Pipe             = "Base.Pipe",
				RubberBand       = "Base.RubberBand",
				Rubberducky      = "Base.Rubberducky",
				Rubberducky2     = "Base.Rubberducky2",
				SoccerBall       = "Base.SoccerBall",
				Sparklers        = "Base.Sparklers",
				TennisBall       = "Base.TennisBall",
				ToiletPaper      = "Base.ToiletPaper",
				Toothbrush       = "Base.Toothbrush",
				Torch            = "Base.Torch",
				ToyBear          = "Base.ToyBear",
				ToyCar           = "Base.ToyCar",
				Tweezers         = "Base.Tweezers",
				Yoyo             = "Base.Yoyo",
				ElectronicsScrap = "Base.ElectronicsScrap",
				Hairspray        = "Base.Hairspray",
				GunPowder        = "Base.GunPowder",
				CameraFilm       = "Base.CameraFilm",
				CameraExpensive  = "Base.CameraExpensive",
				CameraDisposable = "Base.CameraDisposable",
				Camera           = "Base.Camera",
				LeatherStrips    = "Base.LeatherStrips",
				DenimStrips      = "Base.DenimStrips",
			},
		},
		epic = {
			chance = 5,
			xp = 75,
			items = {
				BucketEmpty  = "Base.BucketEmpty",
				Fertilizer   = "Base.Fertilizer",
				GardenSaw    = "Base.GardenSaw",
				Kettle       = "Base.Kettle",
				MortarPestle = "Base.MortarPestle",
				NailsBox     = "Base.NailsBox",
				Needle       = "Base.Needle",
				RoastingPan  = "Base.RoastingPan",
				Rope         = "Base.Rope",
				Wire         = "Base.Wire",
				MugWhite     = "Base.MugWhite",
				MugRed       = "Base.MugRed",
				Mugl         = "Base.Mugl",
				Spiffo       = "Base.Spiffo",
			},
		},
		legendary = {
			chance = 1,
			xp = 100,
			items = {
				EmptyJar       = "Base.EmptyJar",
				EmptyPetrolCan = "Base.EmptyPetrolCan",
				JarLid         = "Base.JarLid",
				MugSpiffo      = "Base.MugSpiffo",
				SpiffoBig      = "Base.SpiffoBig",
			},
		},
	};
	for rarity, spawnTable in pairs(trashItems) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageDefs[itemName] = {
				type = itemFullName,
				xp = spawnTable.xp,
				categories = { "Trash" },
				zones = {
					Forest      = spawnTable.chance,
					DeepForest  = spawnTable.chance,
					Vegitation  = spawnTable.chance,
					FarmLand    = spawnTable.chance,
					Farm        = spawnTable.chance,
					TrailerPark = spawnTable.chance,
					TownZone    = spawnTable.chance,
					Nav         = spawnTable.chance,
				},
				forceOutside = false,
				canBeAboveFloor = true,
				itemSizeModifier = 1.0,
				isItemOverrideSize = true,
			};
		end;
	end;
end

generateJunkDefs();