--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

ContainerButtonIcons = ContainerButtonIcons or {}

local t = {}
t.cabinet = getTexture("media/ui/Container_Cabinet.png")
t.campfire = getTexture("media/ui/Container_Campfire.png")
t.clothingDryer = getTexture("media/ui/Container_ClothingDryer.png")
t.clothingWasher = getTexture("media/ui/Container_ClothingWasher.png")
t.counter = getTexture("media/ui/Container_Counter.png")
t.crate = getTexture("media/ui/Container_Crate.png")
t.drawer = getTexture("media/ui/Container_Drawer.png")
t.femalePerson = getTexture("media/ui/Container_DeadPerson_Female.png")
t.femaleZombie = getTexture("media/ui/Container_DeadPerson_FemaleZombie.png")
t.floor = getTexture("media/ui/Container_Floor.png")
t.freezer = getTexture("media/ui/Container_Freezer.png")
t.fridge = getTexture("media/ui/Container_Fridge.png")
t.garbage = getTexture("media/ui/Container_Garbage.png")
t.glovebox = getTexture("media/ui/Container_GloveCompartment.png")
t.logs = getTexture("media/ui/Item_Logs.png")
t.malePerson = getTexture("media/ui/Container_DeadPerson_Male.png")
t.maleZombie = getTexture("media/ui/Container_DeadPerson_MaleZombie.png")
t.mannequin = getTexture("media/ui/Container_Mannequin.png")
t.medicine = getTexture("media/ui/Container_Medicine.png")
t.microwave = getTexture("media/ui/Container_Microwave.png")
t.oven = getTexture("media/ui/Container_Oven.png")
t.plant = getTexture("media/ui/Container_Plant.png")
t.postBox = getTexture("media/ui/Container_MailBox.png")
t.sack = getTexture("media/ui/Container_Sack.png")
t.seat = getTexture("media/ui/Container_Carseat.png")
t.shelf = getTexture("media/ui/Container_Shelf.png")
t.trunk = getTexture("media/ui/Container_TruckBed.png")
t.vending = getTexture("media/ui/Container_Vendingt.png")

ContainerButtonIcons.barbecue = t.oven
ContainerButtonIcons.bin = t.garbage
ContainerButtonIcons.campfire = t.campfire
ContainerButtonIcons.clothingdryer = t.clothingDryer
ContainerButtonIcons.clothingwasher = t.clothingWasher
ContainerButtonIcons.corn = t.plant
ContainerButtonIcons.counter = t.counter
ContainerButtonIcons.crate = t.crate
ContainerButtonIcons.desk = t.drawer
ContainerButtonIcons.dresser = t.drawer
ContainerButtonIcons.filingcabinet = t.drawer
ContainerButtonIcons.fireplace = t.oven
ContainerButtonIcons.floor = t.floor
ContainerButtonIcons.freezer = t.freezer
ContainerButtonIcons.fridge = t.fridge
ContainerButtonIcons.fruitbusha = t.plant
ContainerButtonIcons.fruitbushb = t.plant
ContainerButtonIcons.fruitbushc = t.plant
ContainerButtonIcons.fruitbushd = t.plant
ContainerButtonIcons.fruitbushe = t.plant
ContainerButtonIcons.garage_storage = t.crate
ContainerButtonIcons.icecream = t.freezer
ContainerButtonIcons.inventoryfemale = t.femaleZombie
ContainerButtonIcons.inventorymale = t.maleZombie
ContainerButtonIcons.logs = t.logs
ContainerButtonIcons.mannequin = t.mannequin
ContainerButtonIcons.medicine = t.medicine
ContainerButtonIcons.metal_shelves = t.shelf
ContainerButtonIcons.microwave = t.microwave
ContainerButtonIcons.militarycrate = t.crate
ContainerButtonIcons.officedrawers = t.drawer
ContainerButtonIcons.postbox = t.postBox
ContainerButtonIcons.shelves = t.shelf
ContainerButtonIcons.sidetable = t.drawer
ContainerButtonIcons.smallbox = t.crate
ContainerButtonIcons.smallcrate = t.crate
ContainerButtonIcons.stove = t.oven
ContainerButtonIcons.vendingGt = t.vending
ContainerButtonIcons.vendingpop = t.vending
ContainerButtonIcons.vendingsnack = t.vending
ContainerButtonIcons.wardrobe = t.cabinet
ContainerButtonIcons.woodstove = t.oven

ContainerButtonIcons.GloveBox = t.glovebox
ContainerButtonIcons.SeatFrontLeft = t.seat
ContainerButtonIcons.SeatFrontRight = t.seat
ContainerButtonIcons.SeatMiddleLeft = t.seat
ContainerButtonIcons.SeatMiddleRight = t.seat
ContainerButtonIcons.SeatRearLeft = t.seat
ContainerButtonIcons.SeatRearRight = t.seat
ContainerButtonIcons.TrailerTrunk = t.trunk
ContainerButtonIcons.TruckBed = t.trunk
ContainerButtonIcons.TruckBedOpen = t.trunk

