-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["appliances_cooking_01_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_24", "appliances_01_26", "none"} }}
overlayMap["appliances_cooking_01_1"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_27", "none"} }}
overlayMap["appliances_cooking_01_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_28", "appliances_01_30", "none"} }}
overlayMap["appliances_cooking_01_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_29", "appliances_01_31", "none"} }}
overlayMap["appliances_cooking_01_8"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "none"} }}
overlayMap["appliances_cooking_01_9"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_33", "appliances_01_35", "none"} }}
overlayMap["appliances_cooking_01_12"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_36", "appliances_01_38", "none"} }}
overlayMap["appliances_cooking_01_13"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_37", "appliances_01_39", "none"} }}
overlayMap["appliances_cooking_01_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_44", "appliances_01_46", "none"} }}
overlayMap["appliances_cooking_01_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_45", "appliances_01_47", "none"} }}
overlayMap["appliances_laundry_01_0"] = {{ name = "other", chance = 2, usage = "", tiles = {"appliances_01_48", "appliances_01_50"} }}
overlayMap["appliances_laundry_01_1"] = {{ name = "other", chance = 2, usage = "", tiles = {"appliances_01_49", "appliances_01_51"} }}
overlayMap["appliances_laundry_01_4"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_52"} }}
overlayMap["appliances_laundry_01_5"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_53"} }}
overlayMap["appliances_laundry_01_6"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_54"} }}
overlayMap["appliances_laundry_01_7"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_55"} }}
overlayMap["appliances_laundry_01_12"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_60"} }}
overlayMap["appliances_laundry_01_13"] = {{ name = "other", chance = 3, usage = "", tiles = {"appliances_01_61"} }}
overlayMap["appliances_refrigeration_01_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_0", "appliances_01_2", "appliances_01_16", "appliances_01_18", "appliances_01_12", "appliances_01_14", "none"} }}
overlayMap["appliances_refrigeration_01_1"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_1", "appliances_01_3", "appliances_01_13", "appliances_01_15", "appliances_01_17", "appliances_01_19", "none"} }}
overlayMap["appliances_refrigeration_01_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_4", "appliances_01_6", "appliances_01_20", "appliances_01_22", "none"} }}
overlayMap["appliances_refrigeration_01_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_5", "appliances_01_7", "appliances_01_21", "appliances_01_23", "none"} }}
overlayMap["appliances_refrigeration_01_8"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_8", "appliances_01_10", "none"} }}
overlayMap["appliances_refrigeration_01_9"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_9", "appliances_01_11", "none"} }}
overlayMap["appliances_refrigeration_01_12"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_0", "appliances_01_2", "appliances_01_16", "appliances_01_18", "appliances_01_12", "appliances_01_14", "none"} }}
overlayMap["appliances_refrigeration_01_13"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_1", "appliances_01_3", "appliances_01_13", "appliances_01_15", "appliances_01_17", "appliances_01_19", "none"} }}
overlayMap["appliances_refrigeration_01_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_4", "appliances_01_6", "appliances_01_20", "appliances_01_22", "none"} }}
overlayMap["appliances_refrigeration_01_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_5", "appliances_01_7", "appliances_01_21", "appliances_01_23", "none"} }}
overlayMap["appliances_refrigeration_01_32"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_0", "appliances_01_2", "appliances_01_16", "appliances_01_18", "appliances_01_12", "appliances_01_14", "none"} }}
overlayMap["appliances_refrigeration_01_33"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_1", "appliances_01_3", "appliances_01_13", "appliances_01_15", "appliances_01_17", "appliances_01_19", "none"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
