-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["fixtures_bathroom_01_24"] = {{ name = "other", chance = 3, usage = "", tiles = {"fixtures_01_24", "fixtures_01_28"} }}
overlayMap["fixtures_bathroom_01_25"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29"} }}
overlayMap["fixtures_bathroom_01_26"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_26", "fixtures_01_30"} }}
overlayMap["fixtures_bathroom_01_27"] = {{ name = "other", chance = 3, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31"} }}
overlayMap["fixtures_bathroom_01_52"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_32", "fixtures_01_36"} }}
overlayMap["fixtures_bathroom_01_53"] = {{ name = "other", chance = 3, usage = "", tiles = {"fixtures_01_33", "fixtures_01_37"} }}
overlayMap["fixtures_bathroom_01_54"] = {{ name = "other", chance = 3, usage = "", tiles = {"fixtures_01_34", "fixtures_01_38"} }}
overlayMap["fixtures_bathroom_01_55"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_35", "fixtures_01_39"} }}
overlayMap["fixtures_sinks_01_4"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_16"} }}
overlayMap["fixtures_sinks_01_5"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_17"} }}
overlayMap["fixtures_sinks_01_6"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_18"} }}
overlayMap["fixtures_sinks_01_7"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_19"} }}
overlayMap["fixtures_sinks_01_8"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_0", "fixtures_01_8"} }}
overlayMap["fixtures_sinks_01_9"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_1", "fixtures_01_9"} }}
overlayMap["fixtures_sinks_01_10"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_2", "fixtures_01_10"} }}
overlayMap["fixtures_sinks_01_11"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_3", "fixtures_01_11"} }}
overlayMap["fixtures_sinks_01_16"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_16", "fixtures_01_20"} }}
overlayMap["fixtures_sinks_01_17"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_17"} }}
overlayMap["fixtures_sinks_01_18"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_18"} }}
overlayMap["fixtures_sinks_01_19"] = {{ name = "other", chance = 2, usage = "", tiles = {"fixtures_01_19"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
