-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["location_business_office_generic_01_16"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_0", "office_01_1"} }}
overlayMap["location_business_office_generic_01_17"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_2", "office_01_3"} }}
overlayMap["location_business_office_generic_01_18"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_16", "office_01_17", "office_01_18", "office_01_19"} }}
overlayMap["location_business_office_generic_01_19"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_20", "office_01_21", "office_01_22", "office_01_23"} }}
overlayMap["location_business_office_generic_01_21"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_16", "office_01_17", "office_01_18", "office_01_19"} }}
overlayMap["location_business_office_generic_01_22"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_20", "office_01_21", "office_01_22", "office_01_23"} }}
overlayMap["location_business_office_generic_01_24"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_8", "office_01_9"} }}
overlayMap["location_business_office_generic_01_25"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_10", "office_01_11"} }}
overlayMap["location_business_office_generic_01_26"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_24", "office_01_25", "office_01_26", "office_01_27"} }}
overlayMap["location_business_office_generic_01_27"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_28", "office_01_29", "office_01_30", "office_01_31"} }}
overlayMap["location_business_office_generic_01_29"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_24", "office_01_25", "office_01_26", "office_01_27"} }}
overlayMap["location_business_office_generic_01_30"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_28", "office_01_29", "office_01_30", "office_01_31"} }}
overlayMap["location_business_office_generic_01_32"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_4", "office_01_5"} }}
overlayMap["location_business_office_generic_01_33"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_6", "office_01_7"} }}
overlayMap["location_business_office_generic_01_34"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_12", "office_01_13"} }}
overlayMap["location_business_office_generic_01_35"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_14", "office_01_15"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
