-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["furniture_seating_indoor_01_8"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_8"} }}
overlayMap["furniture_seating_indoor_01_9"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_9"} }}
overlayMap["furniture_seating_indoor_01_10"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_10"} }}
overlayMap["furniture_seating_indoor_01_11"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_11"} }}
overlayMap["furniture_seating_indoor_01_12"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_12"} }}
overlayMap["furniture_seating_indoor_01_13"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_13"} }}
overlayMap["furniture_seating_indoor_01_14"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_14"} }}
overlayMap["furniture_seating_indoor_01_15"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_15"} }}
overlayMap["furniture_seating_indoor_01_16"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_16"} }}
overlayMap["furniture_seating_indoor_01_17"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_17"} }}
overlayMap["furniture_seating_indoor_01_18"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_18"} }}
overlayMap["furniture_seating_indoor_01_19"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_19"} }}
overlayMap["furniture_seating_indoor_01_20"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_20"} }}
overlayMap["furniture_seating_indoor_01_21"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_21"} }}
overlayMap["furniture_seating_indoor_01_22"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_22"} }}
overlayMap["furniture_seating_indoor_01_23"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_23"} }}
overlayMap["furniture_seating_indoor_01_24"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_24"} }}
overlayMap["furniture_seating_indoor_01_25"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_25"} }}
overlayMap["furniture_seating_indoor_01_26"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_26"} }}
overlayMap["furniture_seating_indoor_01_27"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_27"} }}
overlayMap["furniture_seating_indoor_01_28"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_28"} }}
overlayMap["furniture_seating_indoor_01_29"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_29"} }}
overlayMap["furniture_seating_indoor_01_30"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_30"} }}
overlayMap["furniture_seating_indoor_01_31"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_31"} }}
overlayMap["furniture_seating_indoor_01_32"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_32"} }}
overlayMap["furniture_seating_indoor_01_33"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_33"} }}
overlayMap["furniture_seating_indoor_01_34"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_34"} }}
overlayMap["furniture_seating_indoor_01_35"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_35"} }}
overlayMap["furniture_seating_indoor_01_36"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_36"} }}
overlayMap["furniture_seating_indoor_01_37"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_37"} }}
overlayMap["furniture_seating_indoor_01_38"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_38"} }}
overlayMap["furniture_seating_indoor_01_39"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_39"} }}
overlayMap["furniture_seating_indoor_01_46"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_46"} }}
overlayMap["furniture_seating_indoor_01_47"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_47"} }}
overlayMap["furniture_seating_indoor_02_24"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_56"} }}
overlayMap["furniture_seating_indoor_02_25"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_57"} }}
overlayMap["furniture_seating_indoor_02_26"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_58"} }}
overlayMap["furniture_seating_indoor_02_27"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_59"} }}
overlayMap["furniture_seating_indoor_02_28"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_60"} }}
overlayMap["furniture_seating_indoor_02_29"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_61"} }}
overlayMap["furniture_seating_indoor_02_30"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_62"} }}
overlayMap["furniture_seating_indoor_02_31"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_63"} }}
overlayMap["furniture_seating_indoor_02_32"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_24"} }}
overlayMap["furniture_seating_indoor_02_34"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_26"} }}
overlayMap["furniture_seating_indoor_02_35"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_27"} }}
overlayMap["furniture_seating_indoor_02_40"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_32"} }}
overlayMap["furniture_seating_indoor_02_41"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_33"} }}
overlayMap["furniture_seating_indoor_02_42"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_34"} }}
overlayMap["furniture_seating_indoor_02_43"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_35"} }}
overlayMap["furniture_seating_indoor_03_8"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_56"} }}
overlayMap["furniture_seating_indoor_03_9"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_57"} }}
overlayMap["furniture_seating_indoor_03_10"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_58"} }}
overlayMap["furniture_seating_indoor_03_11"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_59"} }}
overlayMap["furniture_seating_indoor_03_12"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_60"} }}
overlayMap["furniture_seating_indoor_03_13"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_61"} }}
overlayMap["furniture_seating_indoor_03_14"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_62"} }}
overlayMap["furniture_seating_indoor_03_15"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_63"} }}
overlayMap["furniture_seating_indoor_03_16"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_0"} }}
overlayMap["furniture_seating_indoor_03_17"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_1"} }}
overlayMap["furniture_seating_indoor_03_18"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_2"} }}
overlayMap["furniture_seating_indoor_03_19"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_3"} }}
overlayMap["furniture_seating_indoor_03_20"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_4"} }}
overlayMap["furniture_seating_indoor_03_21"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_5"} }}
overlayMap["furniture_seating_indoor_03_22"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_6"} }}
overlayMap["furniture_seating_indoor_03_23"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_7"} }}
overlayMap["furniture_seating_indoor_03_24"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_8"} }}
overlayMap["furniture_seating_indoor_03_25"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_9"} }}
overlayMap["furniture_seating_indoor_03_26"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_10"} }}
overlayMap["furniture_seating_indoor_03_27"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_11"} }}
overlayMap["furniture_seating_indoor_03_28"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_12"} }}
overlayMap["furniture_seating_indoor_03_29"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_13"} }}
overlayMap["furniture_seating_indoor_03_30"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_14"} }}
overlayMap["furniture_seating_indoor_03_31"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_15"} }}
overlayMap["furniture_seating_indoor_03_32"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_16"} }}
overlayMap["furniture_seating_indoor_03_33"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_17"} }}
overlayMap["furniture_seating_indoor_03_34"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_18"} }}
overlayMap["furniture_seating_indoor_03_35"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_19"} }}
overlayMap["furniture_seating_indoor_03_36"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_20"} }}
overlayMap["furniture_seating_indoor_03_37"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_21"} }}
overlayMap["furniture_seating_indoor_03_38"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_22"} }}
overlayMap["furniture_seating_indoor_03_39"] = {{ name = "other", chance = 2, usage = "", tiles = {"seating_01_23"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
