-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["furniture_storage_01_8"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_8", "storage_01_10", "storage_01_16", "storage_01_18", "none"} }}
overlayMap["furniture_storage_01_9"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_17", "storage_01_11", "storage_01_9", "storage_01_19", "none"} }}
overlayMap["furniture_storage_01_10"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_0", "storage_01_2", "storage_01_4", "storage_01_6", "none"} }}
overlayMap["furniture_storage_01_11"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_1", "storage_01_3", "storage_01_5", "storage_01_7", "none"} }}
overlayMap["furniture_storage_01_12"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_12", "storage_01_14", "storage_01_20", "storage_01_22", "none"} }}
overlayMap["furniture_storage_01_13"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_23", "storage_01_13", "storage_01_15", "storage_01_21", "none"} }}
overlayMap["furniture_storage_01_14"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_2", "storage_01_4", "storage_01_0", "storage_01_6", "none"} }}
overlayMap["furniture_storage_01_15"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_1", "storage_01_3", "storage_01_5", "storage_01_7", "none"} }}
overlayMap["furniture_storage_01_32"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_32", "storage_01_34", "storage_01_40", "storage_01_42", "none"} }}
overlayMap["furniture_storage_01_33"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_33", "storage_01_41", "storage_01_35", "storage_01_43", "none"} }}
overlayMap["furniture_storage_01_34"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_2", "storage_01_4", "storage_01_0", "storage_01_6", "none"} }}
overlayMap["furniture_storage_01_35"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_1", "storage_01_3", "storage_01_5", "storage_01_7", "none"} }}
overlayMap["furniture_storage_01_40"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_48", "storage_01_56", "storage_01_50", "storage_01_58", "none"} }}
overlayMap["furniture_storage_01_41"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_49", "storage_01_57", "storage_01_51", "storage_01_59", "none"} }}
overlayMap["furniture_storage_01_42"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_52", "storage_01_54", "storage_01_60", "storage_01_62", "none"} }}
overlayMap["furniture_storage_01_43"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_53", "storage_01_55", "storage_01_63", "storage_01_61", "none"} }}
overlayMap["furniture_storage_01_44"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_2", "storage_01_4", "storage_01_0", "storage_01_6", "none"} }}
overlayMap["furniture_storage_01_45"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_1", "storage_01_3", "storage_01_5", "storage_01_7", "none"} }}
overlayMap["furniture_storage_01_46"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_52", "storage_01_54", "storage_01_60", "storage_01_62", "none"} }}
overlayMap["furniture_storage_01_47"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_53", "storage_01_55", "storage_01_63", "storage_01_61", "none"} }}
overlayMap["furniture_storage_01_52"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"storage_01_44"} }}
overlayMap["furniture_storage_01_53"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"storage_01_45"} }}
overlayMap["furniture_storage_01_54"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"storage_01_46"} }}
overlayMap["furniture_storage_01_55"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"storage_01_47"} }}
overlayMap["furniture_storage_02_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_24", "storage_01_28", "storage_01_30", "none"} }}
overlayMap["furniture_storage_02_1"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_25", "storage_01_29", "storage_01_31", "none"} }}
overlayMap["furniture_storage_02_2"] = {{ name = "other", chance = 2, usage = "", tiles = {"storage_01_26"} }}
overlayMap["furniture_storage_02_3"] = {{ name = "other", chance = 2, usage = "", tiles = {"storage_01_27"} }}
overlayMap["furniture_storage_02_4"] = {{ name = "other", chance = 5, usage = "", tiles = {"storage_01_38"} }}
overlayMap["furniture_storage_02_5"] = {{ name = "other", chance = 5, usage = "", tiles = {"storage_01_39"} }}
overlayMap["furniture_storage_02_12"] = {{ name = "other", chance = 5, usage = "", tiles = {"storage_01_36"} }}
overlayMap["furniture_storage_02_13"] = {{ name = "other", chance = 5, usage = "", tiles = {"storage_01_37"} }}
overlayMap["location_community_medical_01_36"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_64", "storage_01_68", "none"} }}
overlayMap["location_community_medical_01_37"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_65", "storage_01_69", "none"} }}
overlayMap["location_community_medical_01_38"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_66", "storage_01_70", "none"} }}
overlayMap["location_community_medical_01_39"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"storage_01_67", "storage_01_71", "none"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
