-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["walls_garage_01_32"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_0", "walls_house_smooth_01_4", "walls_house_smooth_01_16", "walls_house_smooth_01_20", "walls_house_smooth_01_18", "walls_house_smooth_01_22"} }}
overlayMap["walls_garage_01_33"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_1", "walls_house_smooth_01_5", "walls_house_smooth_01_17", "walls_house_smooth_01_19", "walls_house_smooth_01_21", "walls_house_smooth_01_23"} }}
overlayMap["walls_garage_01_34"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_2", "walls_house_smooth_01_6"} }}
overlayMap["walls_garage_01_36"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_24", "walls_house_smooth_01_28", "walls_house_smooth_01_40", "walls_house_smooth_01_42", "walls_house_smooth_01_44", "walls_house_smooth_01_46"} }}
overlayMap["walls_garage_01_37"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_25", "walls_house_smooth_01_29", "walls_house_smooth_01_41", "walls_house_smooth_01_43", "walls_house_smooth_01_45", "walls_house_smooth_01_47"} }}
overlayMap["walls_garage_01_38"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_26", "walls_house_smooth_01_30"} }}
overlayMap["walls_garage_01_40"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_8", "walls_house_smooth_01_12"} }}
overlayMap["walls_garage_01_41"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_9", "walls_house_smooth_01_13"} }}
overlayMap["walls_garage_01_42"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_10", "walls_house_smooth_01_14"} }}
overlayMap["walls_garage_01_43"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_11", "walls_house_smooth_01_15"} }}
overlayMap["walls_garage_01_44"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_32", "walls_house_smooth_01_36"} }}
overlayMap["walls_garage_01_45"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_33", "walls_house_smooth_01_37"} }}
overlayMap["walls_garage_01_46"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_34", "walls_house_smooth_01_38"} }}
overlayMap["walls_garage_01_47"] = {{ name = "other", chance = 9, usage = "", tiles = {"walls_house_smooth_01_35", "walls_house_smooth_01_39"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
