-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["appliances_refrigeration_01_16"] = {{ name = "other", tiles = {"food_01_90", "food_01_94"} }, { name = "other", tiles = {"food_02_90", "food_02_94"} }}
overlayMap["appliances_refrigeration_01_17"] = {{ name = "other", tiles = {"food_01_91", "food_01_95"} }, { name = "other", tiles = {"food_02_91", "food_02_95"} }}
overlayMap["appliances_refrigeration_01_18"] = {{ name = "other", tiles = {"food_01_88", "food_01_92"} }, { name = "other", tiles = {"food_02_88", "food_02_92"} }}
overlayMap["appliances_refrigeration_01_19"] = {{ name = "other", tiles = {"food_01_89", "food_01_93"} }, { name = "other", tiles = {"food_02_89", "food_02_93"} }}
overlayMap["appliances_refrigeration_01_22"] = {{ name = "other", tiles = {"food_01_54", "food_01_62"} }, { name = "other", tiles = {"food_02_54", "food_02_62"} }}
overlayMap["appliances_refrigeration_01_23"] = {{ name = "other", tiles = {"food_01_55", "food_01_63"} }, { name = "other", tiles = {"food_02_55", "food_02_63"} }}
overlayMap["appliances_refrigeration_01_40"] = {{ name = "other", tiles = {"food_01_54", "food_01_62"} }, { name = "other", tiles = {"food_02_54", "food_02_62"} }}
overlayMap["appliances_refrigeration_01_41"] = {{ name = "other", tiles = {"food_01_55", "food_01_63"} }, { name = "other", tiles = {"food_02_55", "food_02_63"} }}
overlayMap["carpentry_02_64"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["carpentry_02_65"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["carpentry_02_68"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["carpentry_02_69"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_0"] = {{ name = "other", tiles = {"books&misc_01_0", "books&misc_01_1"} }, { name = "other", tiles = {"books&misc_02_0", "books&misc_02_1"} }}
overlayMap["furniture_shelving_01_1"] = {{ name = "other", tiles = {"books&misc_01_2", "books&misc_01_4"} }, { name = "other", tiles = {"books&misc_02_2", "books&misc_02_4"} }}
overlayMap["furniture_shelving_01_2"] = {{ name = "other", tiles = {"books&misc_01_3", "books&misc_01_5"} }, { name = "other", tiles = {"books&misc_02_3", "books&misc_02_5"} }}
overlayMap["furniture_shelving_01_3"] = {{ name = "other", tiles = {"books&misc_01_8", "books&misc_01_10"} }, { name = "other", tiles = {"books&misc_02_8", "books&misc_02_10"} }}
overlayMap["furniture_shelving_01_4"] = {{ name = "other", tiles = {"books&misc_01_9", "books&misc_01_11"} }, { name = "other", tiles = {"books&misc_02_9", "books&misc_02_11"} }}
overlayMap["furniture_shelving_01_8"] = {{ name = "other", tiles = {"books&misc_01_0", "books&misc_01_1"} }}
overlayMap["furniture_shelving_01_9"] = {{ name = "other", tiles = {"books&misc_01_16", "books&misc_01_18"} }, { name = "other", tiles = {"books&misc_02_16", "books&misc_02_18"} }}
overlayMap["furniture_shelving_01_10"] = {{ name = "other", tiles = {"books&misc_01_17", "books&misc_01_19"} }, { name = "other", tiles = {"books&misc_02_17", "books&misc_02_19"} }}
overlayMap["furniture_shelving_01_16"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_01_17"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_01_18"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_01_19"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_01_20"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_01_21"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_01_22"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_01_23"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_01_24"] = {{ name = "other", tiles = {"books&misc_01_24", "books&misc_01_28"} }, { name = "other", tiles = {"books&misc_02_24", "books&misc_02_28"} }}
overlayMap["furniture_shelving_01_25"] = {{ name = "other", tiles = {"books&misc_01_25", "books&misc_01_29"} }, { name = "other", tiles = {"books&misc_02_25", "books&misc_02_29"} }}
overlayMap["furniture_shelving_01_26"] = {{ name = "other", tiles = {"books&misc_01_26", "books&misc_01_30"} }, { name = "other", tiles = {"books&misc_02_26", "books&misc_02_30"} }}
overlayMap["furniture_shelving_01_27"] = {{ name = "other", tiles = {"books&misc_01_27", "books&misc_01_31"} }, { name = "other", tiles = {"books&misc_02_27", "books&misc_02_31"} }}
overlayMap["furniture_shelving_01_28"] = {{ name = "other", tiles = {"books&misc_01_48", "books&misc_01_52"} }, { name = "other", tiles = {"books&misc_02_48", "books&misc_02_52"} }}
overlayMap["furniture_shelving_01_29"] = {{ name = "other", tiles = {"books&misc_01_49", "books&misc_01_53"} }, { name = "other", tiles = {"books&misc_02_49", "books&misc_02_53"} }}
overlayMap["furniture_shelving_01_30"] = {{ name = "other", tiles = {"books&misc_01_50", "books&misc_01_54"} }, { name = "other", tiles = {"books&misc_02_50", "books&misc_02_54"} }}
overlayMap["furniture_shelving_01_31"] = {{ name = "other", tiles = {"books&misc_01_51", "books&misc_01_55"} }, { name = "other", tiles = {"books&misc_02_51", "books&misc_02_55"} }}
overlayMap["furniture_shelving_01_32"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_33"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_34"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_35"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_36"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_37"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_40"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_01_41"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_01_44"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_01_45"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["location_entertainment_theatre_01_120"] = {{ name = "other", tiles = {"books&misc_01_112", "books&misc_01_116"} }}
overlayMap["location_entertainment_theatre_01_121"] = {{ name = "other", tiles = {"books&misc_01_113", "books&misc_01_117"} }}
overlayMap["location_entertainment_theatre_01_122"] = {{ name = "other", tiles = {"books&misc_01_114", "books&misc_01_118"} }}
overlayMap["location_entertainment_theatre_01_123"] = {{ name = "other", tiles = {"books&misc_01_115", "books&misc_01_119"} }}
overlayMap["location_entertainment_theatre_01_128"] = {{ name = "other", tiles = {"books&misc_01_120", "books&misc_01_124"} }}
overlayMap["location_entertainment_theatre_01_129"] = {{ name = "other", tiles = {"books&misc_01_121", "books&misc_01_125"} }}
overlayMap["location_entertainment_theatre_01_130"] = {{ name = "other", tiles = {"books&misc_01_122", "books&misc_01_126"} }}
overlayMap["location_entertainment_theatre_01_131"] = {{ name = "other", tiles = {"books&misc_01_123", "books&misc_01_127"} }}
overlayMap["location_restaurant_bar_01_29"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }, { name = "other", tiles = {"food_02_78", "food_02_86"} }}
overlayMap["location_restaurant_bar_01_30"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }, { name = "other", tiles = {"food_02_78", "food_02_86"} }}
overlayMap["location_restaurant_bar_01_31"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }, { name = "other", tiles = {"food_02_78", "food_02_86"} }}
overlayMap["location_restaurant_bar_01_37"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }, { name = "other", tiles = {"food_02_79", "food_02_87"} }}
overlayMap["location_restaurant_bar_01_38"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }, { name = "other", tiles = {"food_02_79", "food_02_87"} }}
overlayMap["location_restaurant_bar_01_39"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }, { name = "other", tiles = {"food_02_79", "food_02_87"} }}
overlayMap["location_restaurant_pie_01_48"] = {{ name = "other", tiles = {"food_01_24", "food_01_28"} }, { name = "other", tiles = {"food_02_24", "food_02_28"} }}
overlayMap["location_restaurant_pie_01_49"] = {{ name = "other", tiles = {"food_01_25", "food_01_29"} }, { name = "other", tiles = {"food_02_25", "food_02_29"} }}
overlayMap["location_restaurant_pie_01_50"] = {{ name = "other", tiles = {"food_01_26", "food_01_30"} }, { name = "other", tiles = {"food_02_26", "food_02_30"} }}
overlayMap["location_restaurant_pie_01_51"] = {{ name = "other", tiles = {"food_01_27", "food_01_31"} }, { name = "other", tiles = {"food_02_27", "food_02_31"} }}
overlayMap["location_restaurant_pie_01_52"] = {{ name = "other", tiles = {"food_01_32", "food_01_36"} }, { name = "other", tiles = {"food_02_32", "food_02_36"} }}
overlayMap["location_restaurant_pie_01_53"] = {{ name = "other", tiles = {"food_01_33", "food_01_37"} }, { name = "other", tiles = {"food_02_33", "food_02_37"} }}
overlayMap["location_restaurant_pie_01_54"] = {{ name = "other", tiles = {"food_01_34", "food_01_38"} }, { name = "other", tiles = {"food_02_34", "food_02_38"} }}
overlayMap["location_restaurant_pie_01_55"] = {{ name = "other", tiles = {"food_01_35", "food_01_39"} }, { name = "other", tiles = {"food_02_39", "food_02_35"} }}
overlayMap["location_restaurant_seahorse_01_56"] = {{ name = "other", tiles = {"food_01_26", "food_01_30"} }, { name = "other", tiles = {"food_02_26", "food_02_30"} }}
overlayMap["location_restaurant_seahorse_01_57"] = {{ name = "other", tiles = {"food_01_27", "food_01_31"} }, { name = "other", tiles = {"food_02_27", "food_02_31"} }}
overlayMap["location_restaurant_seahorse_01_58"] = {{ name = "other", tiles = {"food_01_24", "food_01_28"} }, { name = "other", tiles = {"food_02_24", "food_02_28"} }}
overlayMap["location_restaurant_seahorse_01_59"] = {{ name = "other", tiles = {"food_01_25", "food_01_29"} }, { name = "other", tiles = {"food_02_25", "food_02_29"} }}
overlayMap["location_shop_fossoil_01_34"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }, { name = "other", tiles = {"books&misc_02_12", "books&misc_02_20"} }}
overlayMap["location_shop_fossoil_01_35"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }, { name = "other", tiles = {"books&misc_02_13", "books&misc_02_21"} }}
overlayMap["location_shop_fossoil_01_36"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }, { name = "other", tiles = {"books&misc_02_14", "books&misc_02_22"} }}
overlayMap["location_shop_fossoil_01_37"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }, { name = "other", tiles = {"books&misc_02_15", "books&misc_02_23"} }}
overlayMap["location_shop_generic_01_0"] = {{ name = "other", tiles = {"food_01_0", "food_01_2"} }, { name = "other", tiles = {"food_02_0", "food_02_2"} }}
overlayMap["location_shop_generic_01_1"] = {{ name = "other", tiles = {"food_01_1", "food_01_3"} }, { name = "other", tiles = {"food_02_1", "food_02_3"} }}
overlayMap["location_shop_generic_01_8"] = {{ name = "other", tiles = {"food_01_8", "food_01_16"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }, { name = "pharmacy", tiles = {"books&misc_01_72", "books&misc_01_80"} }, { name = "pharmacy", tiles = {"books&misc_02_72", "books&misc_02_80"} }}
overlayMap["location_shop_generic_01_9"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "pharmacy", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "pharmacy", tiles = {"books&misc_02_73", "books&misc_02_81"} }}
overlayMap["location_shop_generic_01_10"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "pharmacy", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "pharmacy", tiles = {"books&misc_02_73", "books&misc_02_81"} }}
overlayMap["location_shop_generic_01_11"] = {{ name = "other", tiles = {"food_01_10", "food_01_18"} }, { name = "other", tiles = {"food_02_10", "food_02_18"} }, { name = "pharmacy", tiles = {"books&misc_01_74", "books&misc_01_82"} }, { name = "pharmacy", tiles = {"books&misc_02_74", "books&misc_02_82"} }}
overlayMap["location_shop_generic_01_12"] = {{ name = "other", tiles = {"food_01_11", "food_01_19"} }, { name = "other", tiles = {"food_02_11", "food_02_19"} }, { name = "pharmacy", tiles = {"books&misc_01_75", "books&misc_01_83"} }, { name = "pharmacy", tiles = {"books&misc_02_75", "books&misc_02_83"} }}
overlayMap["location_shop_generic_01_13"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "pharmacy", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "pharmacy", tiles = {"books&misc_02_76", "books&misc_02_84"} }}
overlayMap["location_shop_generic_01_14"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "pharmacy", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "pharmacy", tiles = {"books&misc_02_76", "books&misc_02_84"} }}
overlayMap["location_shop_generic_01_15"] = {{ name = "other", tiles = {"food_01_13", "food_01_21"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }, { name = "pharmacy", tiles = {"books&misc_01_77", "books&misc_01_85"} }, { name = "pharmacy", tiles = {"books&misc_02_77", "books&misc_02_85"} }}
overlayMap["location_shop_generic_01_24"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }, { name = "other", tiles = {"books&misc_02_12", "books&misc_02_20"} }}
overlayMap["location_shop_generic_01_25"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }, { name = "other", tiles = {"books&misc_02_13", "books&misc_02_21"} }}
overlayMap["location_shop_generic_01_26"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }, { name = "other", tiles = {"books&misc_02_14", "books&misc_02_22"} }}
overlayMap["location_shop_generic_01_27"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }, { name = "other", tiles = {"books&misc_02_15", "books&misc_02_23"} }}
overlayMap["location_shop_generic_01_28"] = {{ name = "grocery", tiles = {"food_02_96", "food_02_100"} }, { name = "grocery", tiles = {"food_01_96", "food_01_100"} }, { name = "other", tiles = {"books&misc_01_104", "books&misc_01_108"} }, { name = "other", tiles = {"books&misc_02_104", "books&misc_02_108"} }}
overlayMap["location_shop_generic_01_29"] = {{ name = "grocery", tiles = {"food_02_97", "food_02_101"} }, { name = "grocery", tiles = {"food_01_97", "food_01_101"} }, { name = "other", tiles = {"books&misc_01_105", "books&misc_01_109"} }, { name = "other", tiles = {"books&misc_02_105", "books&misc_02_109"} }}
overlayMap["location_shop_generic_01_30"] = {{ name = "grocery", tiles = {"food_02_98", "food_02_102"} }, { name = "grocery", tiles = {"food_01_98", "food_01_102"} }, { name = "other", tiles = {"books&misc_01_106", "books&misc_01_110"} }, { name = "other", tiles = {"books&misc_02_106", "books&misc_02_110"} }}
overlayMap["location_shop_generic_01_31"] = {{ name = "grocery", tiles = {"food_02_99", "food_02_103"} }, { name = "grocery", tiles = {"food_01_99", "food_01_103"} }, { name = "other", tiles = {"books&misc_01_107", "books&misc_01_111"} }, { name = "other", tiles = {"books&misc_02_107", "books&misc_02_111"} }}
overlayMap["location_shop_generic_01_32"] = {{ name = "other", tiles = {"food_01_24", "food_01_28"} }, { name = "other", tiles = {"food_02_24", "food_02_28"} }}
overlayMap["location_shop_generic_01_33"] = {{ name = "other", tiles = {"food_01_25", "food_01_29"} }, { name = "other", tiles = {"food_02_25", "food_02_29"} }}
overlayMap["location_shop_generic_01_34"] = {{ name = "other", tiles = {"food_01_26", "food_01_30"} }, { name = "other", tiles = {"food_02_26", "food_02_30"} }}
overlayMap["location_shop_generic_01_35"] = {{ name = "other", tiles = {"food_01_27", "food_01_31"} }, { name = "other", tiles = {"food_02_27", "food_02_31"} }}
overlayMap["location_shop_generic_01_36"] = {{ name = "other", tiles = {"clothing_01_0", "clothing_01_4"} }, { name = "other", tiles = {"clothing_02_0", "clothing_02_4"} }}
overlayMap["location_shop_generic_01_37"] = {{ name = "other", tiles = {"clothing_01_1", "clothing_01_5"} }, { name = "other", tiles = {"clothing_02_1", "clothing_02_5"} }}
overlayMap["location_shop_generic_01_38"] = {{ name = "other", tiles = {"clothing_01_2", "clothing_01_6"} }, { name = "other", tiles = {"clothing_02_2", "clothing_02_6"} }}
overlayMap["location_shop_generic_01_39"] = {{ name = "other", tiles = {"clothing_01_3", "clothing_01_7"} }, { name = "other", tiles = {"clothing_02_3", "clothing_02_7"} }}
overlayMap["location_shop_generic_01_40"] = {{ name = "clothesstore", tiles = {"clothing_01_8", "clothing_01_16"} }, { name = "clothesstore", tiles = {"clothing_02_8", "clothing_02_16"} }, { name = "departmentstore", tiles = {"clothing_01_8", "clothing_01_16"} }, { name = "departmentstore", tiles = {"clothing_02_8", "clothing_02_16"} }, { name = "generalstore", tiles = {"clothing_01_8", "clothing_01_16"} }, { name = "generalstore", tiles = {"clothing_02_8", "clothing_02_16"} }}
overlayMap["location_shop_generic_01_41"] = {{ name = "clothesstore", tiles = {"clothing_01_9", "clothing_01_17"} }, { name = "clothesstore", tiles = {"clothing_02_9", "clothing_02_17"} }, { name = "departmentstore", tiles = {"clothing_01_9", "clothing_01_17"} }, { name = "departmentstore", tiles = {"clothing_02_9", "clothing_02_17"} }, { name = "generalstore", tiles = {"clothing_01_9", "clothing_01_17"} }, { name = "generalstore", tiles = {"clothing_02_9", "clothing_02_17"} }, { name = "other", tiles = {"clothing_02_9", "clothing_02_17"} }}
overlayMap["location_shop_generic_01_46"] = {{ name = "clothesstore", tiles = {"clothing_01_12", "clothing_01_20"} }, { name = "clothesstore", tiles = {"clothing_02_12", "clothing_02_20"} }, { name = "departmentstore", tiles = {"clothing_01_12", "clothing_01_20"} }, { name = "departmentstore", tiles = {"clothing_02_12", "clothing_02_20"} }, { name = "generalstore", tiles = {"clothing_01_12", "clothing_01_20"} }, { name = "generalstore", tiles = {"clothing_02_12", "clothing_02_20"} }, { name = "other", tiles = {"clothing_02_12", "clothing_02_20"} }}
overlayMap["location_shop_generic_01_47"] = {{ name = "clothesstore", tiles = {"clothing_01_13", "clothing_01_21"} }, { name = "clothesstore", tiles = {"clothing_02_13", "clothing_02_21"} }, { name = "departmentstore", tiles = {"clothing_01_13", "clothing_01_21"} }, { name = "departmentstore", tiles = {"clothing_02_13", "clothing_02_21"} }, { name = "generalstore", tiles = {"clothing_01_13", "clothing_01_21"} }, { name = "generalstore", tiles = {"clothing_02_13", "clothing_02_21"} }}
overlayMap["location_shop_generic_01_48"] = {{ name = "other", tiles = {"clothing_01_24", "clothing_01_28"} }, { name = "other", tiles = {"clothing_02_24", "clothing_02_28"} }}
overlayMap["location_shop_generic_01_49"] = {{ name = "other", tiles = {"clothing_01_25", "clothing_01_29"} }, { name = "other", tiles = {"clothing_02_25", "clothing_02_29"} }}
overlayMap["location_shop_generic_01_50"] = {{ name = "other", tiles = {"clothing_01_26", "clothing_01_30"} }, { name = "other", tiles = {"clothing_02_26", "clothing_02_30"} }}
overlayMap["location_shop_generic_01_51"] = {{ name = "other", tiles = {"clothing_01_27", "clothing_01_31"} }, { name = "other", tiles = {"clothing_02_27", "clothing_02_31"} }}
overlayMap["location_shop_generic_01_52"] = {{ name = "other", tiles = {"clothing_01_38", "clothing_01_39"} }, { name = "other", tiles = {"clothing_02_38", "clothing_02_39"} }}
overlayMap["location_shop_generic_01_56"] = {{ name = "clothesstore", tiles = {"clothing_01_32", "clothing_01_40"} }, { name = "clothesstore", tiles = {"clothing_02_32", "clothing_02_40"} }, { name = "clothingstore", tiles = {"clothing_01_32", "clothing_01_40"} }, { name = "departmentstore", tiles = {"clothing_02_32", "clothing_02_40"} }, { name = "generalstore", tiles = {"clothing_01_32", "clothing_01_40"} }, { name = "generalstore", tiles = {"clothing_02_32", "clothing_02_40"} }}
overlayMap["location_shop_generic_01_57"] = {{ name = "clothesstore", tiles = {"clothing_01_33", "clothing_01_41"} }, { name = "clothesstore", tiles = {"clothing_02_33", "clothing_02_41"} }, { name = "generalstore", tiles = {"clothing_01_33", "clothing_01_41"} }, { name = "generalstore", tiles = {"clothing_02_33", "clothing_02_41"} }}
overlayMap["location_shop_generic_01_58"] = {{ name = "clothesstore", tiles = {"clothing_01_34", "clothing_01_42"} }, { name = "clothesstore", tiles = {"clothing_02_34", "clothing_02_42"} }, { name = "generalstore", tiles = {"clothing_01_34", "clothing_01_42"} }, { name = "generalstore", tiles = {"clothing_02_34", "clothing_02_42"} }}
overlayMap["location_shop_generic_01_59"] = {{ name = "clothesstore", tiles = {"clothing_01_35", "clothing_01_43"} }, { name = "clothesstore", tiles = {"clothing_02_35", "clothing_02_43"} }, { name = "generalstore", tiles = {"clothing_01_35", "clothing_01_43"} }, { name = "generalstore", tiles = {"clothing_02_35", "clothing_02_43"} }}
overlayMap["location_shop_generic_01_60"] = {{ name = "clothesstore", tiles = {"clothing_01_36", "clothing_01_44"} }, { name = "clothesstore", tiles = {"clothing_02_36", "clothing_02_44"} }, { name = "generalstore", tiles = {"clothing_01_36", "clothing_01_44"} }, { name = "generalstore", tiles = {"clothing_02_36", "clothing_02_44"} }}
overlayMap["location_shop_generic_01_61"] = {{ name = "clothesstore", tiles = {"clothing_01_37", "clothing_01_45"} }, { name = "clothesstore", tiles = {"clothing_02_37", "clothing_02_45"} }, { name = "generalstore", tiles = {"clothing_01_37", "clothing_01_45"} }, { name = "generalstore", tiles = {"clothing_02_37", "clothing_02_45"} }}
overlayMap["location_shop_generic_01_64"] = {{ name = "other", tiles = {"food_01_48", "food_01_56"} }, { name = "other", tiles = {"food_02_48", "food_02_56"} }}
overlayMap["location_shop_generic_01_65"] = {{ name = "other", tiles = {"food_01_49", "food_01_57"} }, { name = "other", tiles = {"food_02_49", "food_02_57"} }}
overlayMap["location_shop_generic_01_66"] = {{ name = "other", tiles = {"food_01_50", "food_01_58"} }, { name = "other", tiles = {"food_02_50", "food_02_58"} }}
overlayMap["location_shop_generic_01_67"] = {{ name = "other", tiles = {"food_01_51", "food_01_59"} }, { name = "other", tiles = {"food_02_51", "food_02_59"} }}
overlayMap["location_shop_generic_01_68"] = {{ name = "other", tiles = {"food_01_52", "food_01_60"} }, { name = "other", tiles = {"food_02_52", "food_02_60"} }}
overlayMap["location_shop_generic_01_69"] = {{ name = "other", tiles = {"food_01_53", "food_01_61"} }, { name = "other", tiles = {"food_02_53", "food_02_61"} }}
overlayMap["location_shop_generic_01_72"] = {{ name = "grocery", tiles = {"food_01_64", "food_01_68"} }, { name = "grocery", tiles = {"food_02_64", "food_02_68"} }, { name = "other", tiles = {"books&misc_01_64", "books&misc_01_68"} }, { name = "other", tiles = {"books&misc_02_64", "books&misc_02_68"} }}
overlayMap["location_shop_generic_01_73"] = {{ name = "grocery", tiles = {"food_01_65", "food_01_69"} }, { name = "grocery", tiles = {"food_02_65", "food_02_69"} }, { name = "other", tiles = {"books&misc_01_65", "books&misc_01_69"} }, { name = "other", tiles = {"books&misc_02_65", "books&misc_02_69"} }}
overlayMap["location_shop_generic_01_74"] = {{ name = "grocery", tiles = {"food_01_66", "food_01_70"} }, { name = "grocery", tiles = {"food_02_66", "food_02_70"} }, { name = "other", tiles = {"books&misc_01_66", "books&misc_01_70"} }, { name = "other", tiles = {"books&misc_02_66", "books&misc_02_70"} }}
overlayMap["location_shop_generic_01_75"] = {{ name = "grocery", tiles = {"food_01_67", "food_01_71"} }, { name = "grocery", tiles = {"food_02_67", "food_02_71"} }, { name = "other", tiles = {"books&misc_01_67", "books&misc_01_71"} }, { name = "other", tiles = {"books&misc_02_67", "books&misc_02_71"} }}
overlayMap["location_shop_generic_01_80"] = {{ name = "other", tiles = {"food_01_72", "food_01_80"} }, { name = "other", tiles = {"food_02_72", "food_02_80"} }}
overlayMap["location_shop_generic_01_81"] = {{ name = "other", tiles = {"food_01_73", "food_01_81"} }, { name = "other", tiles = {"food_02_73", "food_02_81"} }}
overlayMap["location_shop_generic_01_82"] = {{ name = "other", tiles = {"food_01_74", "food_01_82"} }, { name = "other", tiles = {"food_02_74", "food_02_82"} }}
overlayMap["location_shop_generic_01_83"] = {{ name = "other", tiles = {"food_01_75", "food_01_83"} }, { name = "other", tiles = {"food_02_75", "food_02_83"} }}
overlayMap["location_shop_generic_01_84"] = {{ name = "other", tiles = {"food_01_76", "food_01_84"} }, { name = "other", tiles = {"food_02_76", "food_02_84"} }}
overlayMap["location_shop_generic_01_85"] = {{ name = "other", tiles = {"food_01_77", "food_01_85"} }, { name = "other", tiles = {"food_02_77", "food_02_85"} }}
overlayMap["location_shop_generic_01_86"] = {{ name = "other", tiles = {"clothing_01_48", "clothing_01_50"} }, { name = "other", tiles = {"clothing_02_48", "clothing_02_50"} }}
overlayMap["location_shop_generic_01_87"] = {{ name = "other", tiles = {"clothing_01_49", "clothing_01_51"} }, { name = "other", tiles = {"clothing_02_49", "clothing_02_51"} }}
overlayMap["location_shop_generic_01_88"] = {{ name = "other", tiles = {"food_01_32", "food_01_36"} }, { name = "other", tiles = {"food_02_32", "food_02_36"} }}
overlayMap["location_shop_generic_01_89"] = {{ name = "other", tiles = {"food_01_33", "food_01_37"} }, { name = "other", tiles = {"food_02_33", "food_02_37"} }}
overlayMap["location_shop_generic_01_90"] = {{ name = "other", tiles = {"food_01_34", "food_01_38"} }, { name = "other", tiles = {"food_02_34", "food_02_38"} }}
overlayMap["location_shop_generic_01_91"] = {{ name = "other", tiles = {"food_01_35", "food_01_39"} }, { name = "other", tiles = {"food_02_35", "food_02_39"} }}
overlayMap["location_shop_generic_01_92"] = {{ name = "other", tiles = {"food_01_40", "food_01_44"} }, { name = "other", tiles = {"food_02_40", "food_02_44"} }}
overlayMap["location_shop_generic_01_93"] = {{ name = "other", tiles = {"food_01_41", "food_01_45"} }, { name = "other", tiles = {"food_02_41", "food_02_45"} }}
overlayMap["location_shop_generic_01_94"] = {{ name = "other", tiles = {"food_01_42", "food_01_46"} }, { name = "other", tiles = {"food_02_42", "food_02_46"} }}
overlayMap["location_shop_generic_01_95"] = {{ name = "other", tiles = {"food_01_43", "food_01_47"} }, { name = "other", tiles = {"food_02_43", "food_02_47"} }}
overlayMap["location_shop_generic_01_96"] = {{ name = "gunstore", tiles = {"weapons_01_0", "weapons_01_8"} }, { name = "gunstore", tiles = {"weapons_01_16", "weapons_01_24"} }, { name = "other", tiles = {"books&misc_01_88", "books&misc_01_96"} }, { name = "other", tiles = {"books&misc_02_88", "books&misc_02_96"} }}
overlayMap["location_shop_generic_01_97"] = {{ name = "gunstore", tiles = {"weapons_01_1", "weapons_01_9"} }, { name = "gunstore", tiles = {"weapons_01_17", "weapons_01_25"} }, { name = "other", tiles = {"books&misc_01_89", "books&misc_01_97"} }, { name = "other", tiles = {"books&misc_02_89", "books&misc_02_97"} }}
overlayMap["location_shop_generic_01_98"] = {{ name = "gunstore", tiles = {"weapons_01_2", "weapons_01_10"} }, { name = "gunstore", tiles = {"weapons_01_18", "weapons_01_26"} }, { name = "other", tiles = {"books&misc_01_90", "books&misc_01_98"} }, { name = "other", tiles = {"books&misc_02_90", "books&misc_02_98"} }}
overlayMap["location_shop_generic_01_99"] = {{ name = "gunstore", tiles = {"weapons_01_3", "weapons_01_11"} }, { name = "gunstore", tiles = {"weapons_01_19", "weapons_01_27"} }, { name = "other", tiles = {"books&misc_01_91", "books&misc_01_99"} }, { name = "other", tiles = {"books&misc_02_91", "books&misc_02_99"} }}
overlayMap["location_shop_generic_01_100"] = {{ name = "gunstore", tiles = {"weapons_01_4", "weapons_01_12"} }, { name = "gunstore", tiles = {"weapons_01_20", "weapons_01_28"} }, { name = "other", tiles = {"books&misc_01_92", "books&misc_01_100"} }, { name = "other", tiles = {"books&misc_02_92", "books&misc_02_100"} }}
overlayMap["location_shop_generic_01_101"] = {{ name = "gunstore", tiles = {"weapons_01_5", "weapons_01_13"} }, { name = "gunstore", tiles = {"weapons_01_21", "weapons_01_29"} }, { name = "other", tiles = {"books&misc_01_93", "books&misc_01_101"} }, { name = "other", tiles = {"books&misc_02_93", "books&misc_02_101"} }}
overlayMap["location_shop_generic_01_102"] = {{ name = "gunstore", tiles = {"weapons_01_6", "weapons_01_14"} }, { name = "gunstore", tiles = {"weapons_01_22", "weapons_01_30"} }, { name = "other", tiles = {"books&misc_01_94", "books&misc_01_102"} }, { name = "other", tiles = {"books&misc_02_94", "books&misc_02_102"} }}
overlayMap["location_shop_generic_01_103"] = {{ name = "gunstore", tiles = {"weapons_01_7", "weapons_01_15"} }, { name = "gunstore", tiles = {"weapons_01_23", "weapons_01_31"} }, { name = "other", tiles = {"books&misc_01_95", "books&misc_01_103"} }, { name = "other", tiles = {"books&misc_02_95", "books&misc_02_103"} }}
overlayMap["location_shop_greenes_01_24"] = {{ name = "other", tiles = {"food_01_32", "food_01_36"} }, { name = "other", tiles = {"food_02_32", "food_02_36"} }}
overlayMap["location_shop_greenes_01_25"] = {{ name = "other", tiles = {"food_01_33", "food_01_37"} }, { name = "other", tiles = {"food_02_33", "food_02_37"} }}
overlayMap["location_shop_greenes_01_26"] = {{ name = "other", tiles = {"food_01_34", "food_01_38"} }, { name = "other", tiles = {"food_02_34", "food_02_38"} }}
overlayMap["location_shop_greenes_01_27"] = {{ name = "other", tiles = {"food_01_35", "food_01_39"} }, { name = "other", tiles = {"food_02_35", "food_02_39"} }}
overlayMap["location_shop_greenes_01_28"] = {{ name = "other", tiles = {"food_01_40", "food_01_44"} }, { name = "other", tiles = {"food_02_40", "food_02_44"} }}
overlayMap["location_shop_greenes_01_29"] = {{ name = "other", tiles = {"food_01_41", "food_01_45"} }, { name = "other", tiles = {"food_02_41", "food_02_45"} }}
overlayMap["location_shop_greenes_01_30"] = {{ name = "other", tiles = {"food_01_42", "food_01_46"} }, { name = "other", tiles = {"food_02_42", "food_02_46"} }}
overlayMap["location_shop_greenes_01_31"] = {{ name = "other", tiles = {"food_01_43", "food_01_47"} }, { name = "other", tiles = {"food_02_43", "food_02_47"} }}
overlayMap["location_shop_greenes_01_56"] = {{ name = "other", tiles = {"food_01_8", "food_01_16"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["location_shop_greenes_01_57"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_greenes_01_58"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_greenes_01_59"] = {{ name = "other", tiles = {"food_01_10", "food_01_18"} }, { name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["location_shop_greenes_01_60"] = {{ name = "other", tiles = {"food_01_11", "food_01_19"} }, { name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["location_shop_greenes_01_61"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_greenes_01_62"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_greenes_01_63"] = {{ name = "other", tiles = {"food_01_13", "food_01_21"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["location_shop_zippee_01_8"] = {{ name = "other", tiles = {"food_01_8", "food_01_16"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["location_shop_zippee_01_9"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_zippee_01_10"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_zippee_01_11"] = {{ name = "other", tiles = {"food_01_10", "food_01_18"} }, { name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["location_shop_zippee_01_12"] = {{ name = "other", tiles = {"food_01_11", "food_01_19"} }, { name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["location_shop_zippee_01_13"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_zippee_01_14"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_zippee_01_15"] = {{ name = "other", tiles = {"food_01_13", "food_01_21"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["location_shop_zippee_01_24"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }, { name = "other", tiles = {"books&misc_02_12", "books&misc_02_20"} }}
overlayMap["location_shop_zippee_01_25"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }, { name = "other", tiles = {"books&misc_02_13", "books&misc_02_21"} }}
overlayMap["location_shop_zippee_01_26"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }, { name = "other", tiles = {"books&misc_02_14", "books&misc_02_22"} }}
overlayMap["location_shop_zippee_01_27"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }, { name = "other", tiles = {"books&misc_02_15", "books&misc_02_23"} }}
overlayMap["trashcontainers_01_17"] = {{ name = "other", tiles = {"trash&junk_01_0", "trash&junk_01_1"} }, { name = "other", tiles = {"trash&junk_01_8", "trash&junk_01_9"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
