package fmod.fmod;

public enum FMOD_STUDIO_EVENT_CALLBACK_TYPE {
   FMOD_STUDIO_EVENT_CALLBACK_CREATED(1),
   FMOD_STUDIO_EVENT_CALLBACK_DESTROYED(2),
   FMOD_STUDIO_EVENT_CALLBACK_STARTING(4),
   FMOD_STUDIO_EVENT_CALLBACK_STARTED(8),
   FMOD_STUDIO_EVENT_CALLBACK_RESTARTED(16),
   FMOD_STUDIO_EVENT_CALLBACK_STOPPED(32),
   FMOD_STUDIO_EVENT_CALLBACK_START_FAILED(64),
   FMOD_STUDIO_EVENT_CALLBACK_CREATE_PROGRAMMER_SOUND(128),
   FMOD_STUDIO_EVENT_CALLBACK_DESTROY_PROGRAMMER_SOUND(256),
   FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_CREATED(512),
   FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_DESTROYED(1024),
   FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_MARKER(2048),
   FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_BEAT(4096),
   FMOD_STUDIO_EVENT_CALLBACK_SOUND_PLAYED(8192),
   FMOD_STUDIO_EVENT_CALLBACK_SOUND_STOPPED(16384),
   FMOD_STUDIO_EVENT_CALLBACK_REAL_TO_VIRTUAL(32768),
   FMOD_STUDIO_EVENT_CALLBACK_VIRTUAL_TO_REAL(65536),
   FMOD_STUDIO_EVENT_CALLBACK_START_EVENT_COMMAND(131072),
   FMOD_STUDIO_EVENT_CALLBACK_ALL(-1);

   public final int bit;

   private FMOD_STUDIO_EVENT_CALLBACK_TYPE(int var3) {
      this.bit = var3;
   }

   // $FF: synthetic method
   private static FMOD_STUDIO_EVENT_CALLBACK_TYPE[] $values() {
      return new FMOD_STUDIO_EVENT_CALLBACK_TYPE[]{FMOD_STUDIO_EVENT_CALLBACK_CREATED, FMOD_STUDIO_EVENT_CALLBACK_DESTROYED, FMOD_STUDIO_EVENT_CALLBACK_STARTING, FMOD_STUDIO_EVENT_CALLBACK_STARTED, FMOD_STUDIO_EVENT_CALLBACK_RESTARTED, FMOD_STUDIO_EVENT_CALLBACK_STOPPED, FMOD_STUDIO_EVENT_CALLBACK_START_FAILED, FMOD_STUDIO_EVENT_CALLBACK_CREATE_PROGRAMMER_SOUND, FMOD_STUDIO_EVENT_CALLBACK_DESTROY_PROGRAMMER_SOUND, FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_CREATED, FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_DESTROYED, FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_MARKER, FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_BEAT, FMOD_STUDIO_EVENT_CALLBACK_SOUND_PLAYED, FMOD_STUDIO_EVENT_CALLBACK_SOUND_STOPPED, FMOD_STUDIO_EVENT_CALLBACK_REAL_TO_VIRTUAL, FMOD_STUDIO_EVENT_CALLBACK_VIRTUAL_TO_REAL, FMOD_STUDIO_EVENT_CALLBACK_START_EVENT_COMMAND, FMOD_STUDIO_EVENT_CALLBACK_ALL};
   }
}
