package fmod;

public enum FMOD_STUDIO_EVENT_PROPERTY {
   FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY,
   FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY,
   FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD,
   FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE,
   FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE;

   // $FF: synthetic method
   private static FMOD_STUDIO_EVENT_PROPERTY[] $values() {
      return new FMOD_STUDIO_EVENT_PROPERTY[]{FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD, FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE, FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE};
   }
}
