--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

local group = AttachedLocations.getGroup("Human")
--group:getOrCreateLocation("Knife Belt Back"):setAttachmentName("knife_belt_back")
--group:getOrCreateLocation("Knife Belt Front"):setAttachmentName("knife_belt_front")
--group:getOrCreateLocation("Gun Belt Right"):setAttachmentName("1gun_belt_right")
group:getOrCreateLocation("Walkie Belt Right"):setAttachmentName("walkie_belt_right")
group:getOrCreateLocation("Walkie Belt Left"):setAttachmentName("walkie_belt_left")
group:getOrCreateLocation("MeatCleaver Belt Right"):setAttachmentName("meatcleaver_right")
group:getOrCreateLocation("MeatCleaver Belt Left"):setAttachmentName("meatcleaver_left")
group:getOrCreateLocation("Belt Rotated Right"):setAttachmentName("belt_rotated_right")
group:getOrCreateLocation("Belt Rotated Left"):setAttachmentName("belt_rotated_left")
group:getOrCreateLocation("Rifle On Back"):setAttachmentName("rifle_back")
group:getOrCreateLocation("Rifle On Back with Bag"):setAttachmentName("rifle_back_bag")
group:getOrCreateLocation("Pan On Back with Bag"):setAttachmentName("fryingpan_back_bag")
group:getOrCreateLocation("Saucepan Back with Bag"):setAttachmentName("saucepan_back_bag")
group:getOrCreateLocation("Saucepan Back"):setAttachmentName("saucepan_back")
group:getOrCreateLocation("Wrench Right"):setAttachmentName("wrench_right")
group:getOrCreateLocation("Wrench Left"):setAttachmentName("wrench_left")
group:getOrCreateLocation("Pan On Back"):setAttachmentName("fryingpan_back")
group:getOrCreateLocation("Racket On Back"):setAttachmentName("racket_back")
group:getOrCreateLocation("Racket Back with Bag"):setAttachmentName("racket_back_bag")
group:getOrCreateLocation("Shovel Back with Bag"):setAttachmentName("shovel_back_bag")
group:getOrCreateLocation("Shovel Back"):setAttachmentName("shovel_back")
group:getOrCreateLocation("Big Blade On Back with Bag"):setAttachmentName("big_blade_back_bag")
group:getOrCreateLocation("Big Weapon On Back with Bag"):setAttachmentName("big_w_back_bag")
group:getOrCreateLocation("Guitar"):setAttachmentName("back_guitar");
group:getOrCreateLocation("Guitar Acoustic"):setAttachmentName("back_guitar_acoustic")
group:getOrCreateLocation("Nightstick Right"):setAttachmentName("nightstick_right")
group:getOrCreateLocation("Nightstick Left"):setAttachmentName("nightstick_left")
group:getOrCreateLocation("Belt Right Upside"):setAttachmentName("belt_right_upside")
group:getOrCreateLocation("Belt Left Upside"):setAttachmentName("belt_left_upside")
group:getOrCreateLocation("Blade On Back"):setAttachmentName("blade_back")
group:getOrCreateLocation("Big Weapon On Back"):setAttachmentName("big_w_back")
group:getOrCreateLocation("Belt Right Screwdriver"):setAttachmentName("belt_right_screwdriver")
group:getOrCreateLocation("Belt Left Screwdriver"):setAttachmentName("belt_left_screwdriver")
group:getOrCreateLocation("Belt Right"):setAttachmentName("belt_right")
group:getOrCreateLocation("Belt Left"):setAttachmentName("belt_left")
group:getOrCreateLocation("Holster Right"):setAttachmentName("holster_right")
group:getOrCreateLocation("Holster Left"):setAttachmentName("holster_left")
group:getOrCreateLocation("Crowbar Back"):setAttachmentName("crowbar_back")
group:getOrCreateLocation("Knife Left Leg"):setAttachmentName("knife_left_leg")
group:getOrCreateLocation("Knife Right Leg"):setAttachmentName("knife_right_leg")
group:getOrCreateLocation("Axe Back"):setAttachmentName("axe_back")
group:getOrCreateLocation("Knife Stomach"):setAttachmentName("knife_stomach")
group:getOrCreateLocation("Knife Shoulder"):setAttachmentName("knife_shoulder")
group:getOrCreateLocation("MeatCleaver in Back"):setAttachmentName("meatcleaver_in_back")
group:getOrCreateLocation("JawStab"):setAttachmentName("knife_head")
group:getOrCreateLocation("Stomach"):setAttachmentName("stomach")
group:getOrCreateLocation("Knife in Back"):setAttachmentName("knife_in_back")

if getDebug() then
	group:getOrCreateLocation("OnBack"):setAttachmentName("back")
end

