--***********************************************************
--**                    ROBERT JOHNSON                     **
--***********************************************************

keyBinding = {};

local bind = {};
bind.value = "[Player Control]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Forward";
bind.key = 17;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Backward";
bind.key = 31;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Left";
bind.key = 30;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Right";
bind.key = 32;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Run";
bind.key = 42;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Interact";
bind.key = 18;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Sprint";
bind.key = isSystemMacOS() and Keyboard.KEY_LMETA or Keyboard.KEY_LMENU;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Rotate building";
bind.key = Keyboard.KEY_R;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle mode";
bind.key = Keyboard.KEY_TAB;
table.insert(keyBinding, bind);
bind = {};
bind.value = "CancelAction";
bind.key = Keyboard.KEY_ESCAPE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Combat]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Crouch";
bind.key = Keyboard.KEY_C;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Aim";
bind.key = Keyboard.KEY_LCONTROL;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Melee";
bind.key = Keyboard.KEY_SPACE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Rack Firearm";
bind.key = Keyboard.KEY_X;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ReloadWeapon";
bind.key = Keyboard.KEY_R;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ManualFloorAtk";
bind.key = Keyboard.KEY_LMENU;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Vehicle]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "StartVehicleEngine";
bind.key = Keyboard.KEY_N;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleVehicleHeadlights";
bind.key = Keyboard.KEY_F;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleHeater";
bind.key = Keyboard.KEY_O;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleMechanics";
bind.key = Keyboard.KEY_U;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleHorn";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleRadialMenu";
bind.key = Keyboard.KEY_V;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleSwitchSeat";
bind.key = Keyboard.KEY_Z;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[UI]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle UI";
bind.key = 47;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Crafting UI";
bind.key = 48;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Main Menu";
bind.key = Keyboard.KEY_ESCAPE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Inventory";
bind.key = 23;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Skill Panel";
bind.key = Keyboard.KEY_L;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Health Panel";
bind.key = Keyboard.KEY_H;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Info Panel";
bind.key = Keyboard.KEY_J;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Clothing Protection Panel";
bind.key = Keyboard.KEY_P;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Moveable Panel Mode";
bind.key = 27;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Map";
bind.key = Keyboard.KEY_M;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Take screenshot";
bind.key = 68;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Survival Guide";
bind.key = 59;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Display FPS";
bind.key = 37;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Pause";
bind.key = 60;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Normal Speed";
bind.key = 61;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x1";
bind.key = 62;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x2";
bind.key = 63;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x3";
bind.key = 64;
table.insert(keyBinding, bind);
bind = {};
bind.value = "PanCamera";
bind.key = 0;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Zoom in";
bind.key = 13;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Zoom out";
bind.key = 12;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Hotkeys]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 1";
bind.key = Keyboard.KEY_1;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 2";
bind.key = Keyboard.KEY_2;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 3";
bind.key = Keyboard.KEY_3;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 4";
bind.key = Keyboard.KEY_4;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 5";
bind.key = Keyboard.KEY_5;
table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Handweapon";
--bind.key = 2;
--table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Firearm";
--bind.key = 3;
--table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Stab weapon";
--bind.key = 4;
--table.insert(keyBinding, bind);
bind = {};
bind.value = "Equip/Turn On/Off Light Source";
bind.key = 33;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Multiplayer]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Safety";
bind.key = Keyboard.KEY_G;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle chat";
bind.key = 20;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Alt toggle chat";
bind.key = 28;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Switch chat stream";
bind.key = 15;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Voice]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Enable voice transmit";
bind.key = 56;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[NPC Interaction]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Shout";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Emote";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Debug]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Lua Debugger";
bind.key = Keyboard.KEY_F11;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleLuaConsole";
bind.key = Keyboard.KEY_GRAVE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleGodModeInvisible";
bind.key = Keyboard.KEY_N;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleModelsEnabled";
bind.key = Keyboard.KEY_F3;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleAnimationText";
bind.key = Keyboard.KEY_F6;
table.insert(keyBinding, bind);

